import { readFileSync } from 'node:fs';import { resolve } from 'node:path';import { describe,expect,it } from 'vitest';
const sql=readFileSync(resolve(process.cwd(),'supabase/migrations/20260829000200_create_property_intelligence_opportunity_subject_authority.sql'),'utf8');
describe('Property Intelligence Opportunity-subject authority SQL contract',()=>{
  it('adds exactly three responsibility-specific authority tables',()=>{const tables=[...sql.matchAll(/create table public\.(intelligence_opportunity_subject_\w+)/gi)].map(x=>x[1]);expect(tables).toEqual(['intelligence_opportunity_subject_commands','intelligence_opportunity_subject_proposals','intelligence_opportunity_subject_decisions'])});
  it('keeps entity deduplication separate',()=>{expect(sql).not.toMatch(/alter table public\.intelligence_entity_resolution_(?:proposals|decisions)/i);expect(sql).not.toMatch(/insert into public\.intelligence_entity_resolution_/i)});
  it('serializes command then Opportunity and existing entity authority',()=>{expect(sql).toContain("opportunity-subject-v1|command|");expect(sql).toContain("opportunity-subject-v1|opportunity|");expect(sql).toContain("opportunity-subject-v1|entity|")});
  it('constructs canonical semantics and digest inside PostgreSQL',()=>{expect(sql).toMatch(/canonical_request:=jsonb_build_object/i);expect(sql).toMatch(/extensions\.digest\(convert_to\(canonical_request::text/i);expect(sql).toContain('command_semantics_conflict')});
  it('materializes only confirmed decisions and preserves rejection/ambiguity without Property rows',()=>{expect(sql).toMatch(/if stored_decision='confirmed' then[\s\S]+insert into public\.intelligence_entities/i);expect(sql).toMatch(/decision in \('confirmed','rejected','ambiguous','reversed'\)/i)});
  it('supports explicit correction by reversal without deleting history',()=>{expect(sql).toContain('corrects_proposal_id');expect(sql).toMatch(/insert into public\.intelligence_opportunity_subject_decisions[\s\S]+reversed/i);expect(sql).toMatch(/set relationship_status='reversed'/i);expect(sql).not.toMatch(/delete from public\.intelligence_opportunity_subject/i)});
  it('denies direct mutation and truncation while granting service role only reads and RPC execution',()=>{expect(sql).toMatch(/revoke all on table[\s\S]+from public,anon,authenticated,service_role/i);expect(sql).toMatch(/grant select on table[\s\S]+to service_role/i);expect(sql).toMatch(/before truncate[\s\S]+opportunity_subject/i);expect(sql).toMatch(/grant execute on function[\s\S]+to service_role/i)});
  it('contains no observation, parcel, provider, or underwriting implementation',()=>{expect(sql).not.toMatch(/create table public\.(?:.*observation|.*parcel|.*traffic|.*price)/i);expect(sql).not.toMatch(/insert into public\.(?:.*observation|.*underwriting)|OpenAI|DataTree/i)});
});
