import { describe, expect, it, vi } from 'vitest';
import { addTenant, classifySensitivity, createDefaultEnvelope, createOpportunityRequest, diagnostics, formatCurrency, formatCurrencyPerSf, formatEconomicDetail, formatMultiple, formatNumber, formatPercent, isSensitivityBase, normalizeDecimalInput, normalizeRetailDevelopmentEnvelope, NumericInputValidationError, percentFromDisplay, reorderTenants, saveThenCalculate, SENSITIVITY_AXES } from './format';

describe('Phase 3B UI boundary', () => {
  it('maps creation fields without creating a Deal', () => { const request=createOpportunityRequest({name:'Corner',market:'Austin',askingPrice:'$1,250,000',gla:'21,780',sourceUrl:'https://example.com'}); expect(request).toEqual({opportunity:{name:'Corner',address:{market:'Austin',city:'',state:''},askingPrice:'1250000',existingBuildingAreaSf:'21780'},sourceUrl:'https://example.com'}); expect(JSON.stringify(request)).not.toContain('deal'); });
  it('creates a valid market-mode draft envelope', () => { const envelope=createDefaultEnvelope({askingPrice:'1000000',landAreaSf:'100000',buildingAreaSf:'25000'}); expect(envelope.schemaVersion).toBe('retail-development-persistence-v1'); expect(envelope.engineInput.site).toEqual({landAreaSf:'100000',targetFar:'0.25',landCostPerLandSf:'10'}); expect(envelope.engineInput.leasing.mode).toBe('market'); });
  it('formats rates as percentages and null as em dash', () => { expect(formatPercent('0.0725')).toBe('7.25%'); expect(formatCurrency(null)).toBe('—'); expect(formatNumber(undefined)).toBe('—'); expect(percentFromDisplay('7.25%')).toBe('0.0725'); });
  it('formats arbitrary-precision results without changing their source strings', () => { const source='6877841.091541767366084804089355'; expect(formatCurrency(source)).toBe('$6,877,841'); expect(source).toBe('6877841.091541767366084804089355'); });
  it('formats detailed values according to economic meaning', () => { expect(formatCurrencyPerSf('274.94406915757700674112955729166')).toBe('$274.94 / SF'); expect(formatEconomicDetail('returnOnCost','0.0737')).toBe('7.37%'); expect(formatEconomicDetail('annualizedEquityReturn','-0.0371')).toBe('-3.71%'); expect(formatMultiple('0.91')).toBe('0.91×'); expect(formatNumber('38485.26',' SF')).toBe('38,485.26 SF'); });
  it('formats zero, null, and negative currency intentionally', () => { expect(formatCurrency('0')).toBe('$0'); expect(formatEconomicDetail('grossSaleValue',null)).toBe('—'); expect(formatCurrency('-1250.50',true)).toBe('-$1,250.50'); });
  it('does not expose raw detailed-result precision', () => { const raw='766873.2661125574106766226278488'; const presented=formatEconomicDetail('totalInterimInterest',raw); expect(presented).toBe('$766,873'); expect(presented).not.toContain(raw); });
  it('classifies the sensitivity range from weak through strong', () => { const values=['-10','0','10']; expect(classifySensitivity('-10',values)).toBe('weak'); expect(classifySensitivity('0',values)).toBe('neutral'); expect(classifySensitivity('10',values)).toBe('strong'); });
  it('classifies all-positive sensitivity values by their result range', () => { const values=['5','10','15','20','25']; expect(classifySensitivity('5',values)).toBe('weak'); expect(classifySensitivity('15',values)).toBe('neutral'); expect(classifySensitivity('25',values)).toBe('strong'); });
  it('keeps equal and unavailable sensitivity values neutral', () => { expect(classifySensitivity('7',['7','7','7'])).toBe('neutral'); expect(classifySensitivity(null,['1','2'])).toBe('unavailable'); });
  it('keeps base identification independent from conditional color', () => { const values=['-5','0','5']; expect(isSensitivityBase(1,1,1,1)).toBe(true); expect(isSensitivityBase(1,1,0,0)).toBe(false); expect(classifySensitivity('0',values)).toBe('neutral'); });
  it('does not mutate persisted sensitivity values while classifying', () => { const values=['-1.0000000000001',null,'2.0000000000001']; const original=structuredClone(values); classifySensitivity(values[0],values); expect(values).toEqual(original); });
  it('maps both sensitivity axes explicitly', () => { expect(SENSITIVITY_AXES.unleveredProfit).toEqual({row:'Rent multiplier',column:'Exit cap delta'}); expect(SENSITIVITY_AXES.returnOnCost).toEqual({row:'Hard-cost multiplier',column:'Rent multiplier'}); });
  it('normalizes comma-formatted Site Area without floating point', () => { expect(normalizeDecimalInput('153,941.04', 'site.landAreaSf')).toBe('153941.04'); });
  it('normalizes formatted currency and preserves canonical decimals', () => { expect(normalizeDecimalInput('$1,250,000', 'askingPrice')).toBe('1250000'); expect(normalizeDecimalInput('-1250.005')).toBe('-1250.005'); expect(normalizeDecimalInput('.25')).toBe('.25'); expect(normalizeDecimalInput('')).toBe(''); });
  it.each(['1,23.00', '12,34,567', '1.2.3', '$$100', 'abc', '1 000'])('rejects malformed numeric input %s', value => { expect(() => normalizeDecimalInput(value, 'site.landAreaSf')).toThrow(NumericInputValidationError); });
  it('normalizes every economic decimal in the persistence envelope', () => { const envelope=createDefaultEnvelope(); envelope.engineInput.site.landAreaSf='153,941.04'; envelope.engineInput.development.hardCostPerBuildingSf='$1,250.50'; if(envelope.engineInput.leasing.mode==='market') envelope.engineInput.leasing.rentalRatePerSfYear='2,300.25'; const normalized=normalizeRetailDevelopmentEnvelope(envelope); expect(normalized.engineInput.site.landAreaSf).toBe('153941.04'); expect(normalized.engineInput.development.hardCostPerBuildingSf).toBe('1250.50'); if(normalized.engineInput.leasing.mode==='market') expect(normalized.engineInput.leasing.rentalRatePerSfYear).toBe('2300.25'); });
  it('preserves tenant keys while reordering', () => { let input=createDefaultEnvelope().engineInput; input=addTenant(input,'11111111-1111-4111-8111-111111111111'); input=addTenant(input,'22222222-2222-4222-8222-222222222222'); if(input.leasing.mode!=='tenantRoster')throw new Error(); const moved=reorderTenants(input.leasing.tenants,1,0); expect(moved.map(x=>x.tenantKey)).toEqual(['22222222-2222-4222-8222-222222222222','11111111-1111-4111-8111-111111111111']); expect(moved.map(x=>x.displayOrder)).toEqual([1,2]); });
  it('sequences dirty save before authoritative calculation', async () => { const calls:string[]=[]; const result=await saveThenCalculate(true,async()=>{calls.push('save');return {revision:2}},async saved=>{calls.push(`calculate:${saved?.revision}`);return 'done'}); expect(result).toBe('done'); expect(calls).toEqual(['save','calculate:2']); });
  it('skips saving clean input before calculation', async () => { const save=vi.fn(); const calculate=vi.fn(async()=> 'done'); await saveThenCalculate(false,save,calculate); expect(save).not.toHaveBeenCalled(); expect(calculate).toHaveBeenCalledWith(null); });
  it('separates blocking and warning diagnostics', () => { const result={diagnostics:[{code:'A',severity:'error',path:'site',message:'bad'},{code:'B',severity:'warning',path:'exit',message:'check'}]} as never; const grouped=diagnostics(result); expect(grouped.errors[0].code).toBe('A'); expect(grouped.warnings[0].code).toBe('B'); });
  it.each(['PURSUE','REVIEW','PASS'])('preserves the %s screening category', category => { expect(category).toMatch(/^(PURSUE|REVIEW|PASS)$/); });
});
