'use client';
import { useEffect, useState } from 'react';
import type { ExtractionReviewModel, ExtractionReviewItem } from '@/lib/opportunities/ingestion/extraction-review';
import styles from './OpportunityExtractionReview.module.css';
type Api<T> = { ok: boolean; data: T; error?: { kind: string; message: string } };
export default function OpportunityExtractionReview({ opportunityId, review, loading, error }:{ opportunityId: string; review: ExtractionReviewModel | null; loading: boolean; error: string }) {
  const [current, setCurrent] = useState(review); const [pending, setPending] = useState<Set<string>>(() => new Set()); const [message, setMessage] = useState('');
  useEffect(() => { setCurrent(review); }, [review]);
  async function refresh(stale = false) { const response = await fetch(`/api/opportunities/${opportunityId}/extraction-review`, { cache: 'no-store' }); const json = await response.json() as Api<ExtractionReviewModel | null>; if (json.ok) setCurrent(json.data); if (stale) setMessage('This candidate changed while you were reviewing it. The latest decision has been loaded.'); }
  async function decide(item: ExtractionReviewItem, decision: 'approved' | 'rejected') { if (pending.has(item.candidateId)) return; setPending(value => new Set(value).add(item.candidateId)); setMessage(''); try { const response = await fetch(`/api/opportunities/${opportunityId}/extraction-review/candidates/${item.candidateId}/decision`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ decision, expectedDecisionNumber: item.decisionNumber }) }); const json = await response.json() as Api<ExtractionReviewModel | null>; if (response.status === 409) { await refresh(true); return; } if (!json.ok) throw new Error(json.error?.message ?? 'The decision could not be saved.'); setCurrent(json.data); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'The decision could not be saved.'); } finally { setPending(value => { const next = new Set(value); next.delete(item.candidateId); return next; }); } }
  if (loading) return <section className={styles.panel} aria-busy="true"><p className={styles.muted}>Loading extraction review…</p></section>;
  if (error) return <section className={styles.panel}><h2 className={styles.sectionTitle}>Extraction review</h2><p className={styles.reviewError}>{error}</p></section>;
  if (!current) return <section className={styles.panel}><h2 className={styles.sectionTitle}>Extraction review</h2><p className={styles.muted}>No successful extraction is available for review.</p></section>;
  const reviewed = current.approvedCount + current.rejectedCount;
  const sourcePdf = `/api/opportunities/${opportunityId}/source-pdf`;
  return <section className={`${styles.panel} ${styles.reviewPanel}`} aria-labelledby="extraction-review-title"><div className={styles.reviewHeader}><div><div className={styles.eyebrow}>Extraction review</div><h2 id="extraction-review-title" className={styles.reviewTitle}>{current.factCount} facts extracted</h2><p className={styles.muted}>Extraction completed successfully · Attempt {current.attemptNumber}</p><a href={sourcePdf} target="_blank" rel="noopener noreferrer">Open source PDF ↗</a></div><span className={styles.unreviewedBadge}>{current.unreviewedCount === 0 ? 'Human review complete' : 'Awaiting human review'}</span></div><div className={styles.reviewSummary}><Summary value={String(current.factCount)} label="Facts extracted"/><Summary value={`${current.representedDestinationCount} of ${current.registryDestinationCount}`} label="Registry destinations"/><Summary value={String(current.missingDestinationCount)} label="Fields not found"/><Summary value={`${reviewed} reviewed · ${current.unreviewedCount} remaining`} label={`${current.approvedCount} approved · ${current.rejectedCount} rejected`}/></div><div className={styles.machineNote}><strong>Machine validation passed.</strong> Each extracted fact remains untrusted until a human approves it.</div>{message && <div className={styles.reviewError} role="alert">{message}</div>}{current.groups.map(group => <div className={styles.reviewGroup} key={group.key}><h3>{group.label}</h3><div className={styles.reviewItems}>{group.items.map(item => <CandidateCard item={item} sourcePdf={sourcePdf} busy={pending.has(item.candidateId)} decide={decide} key={item.key}/>)}</div></div>)}<details className={styles.missingSection}><summary>No candidate extracted ({current.missingDestinationCount})</summary><p className={styles.muted}>These fields were not represented in this extraction. Their absence is not a negative factual assertion.</p><div className={styles.missingGrid}>{current.missingDestinations.map(item => <div key={item.fieldPath}><strong>{item.label}</strong><span>No candidate extracted</span></div>)}</div></details></section>;
}
function Summary({value,label}:{value:string;label:string}) { return <div><strong>{value}</strong><span>{label}</span></div>; }
function CandidateCard({item,sourcePdf,busy,decide}:{item:ExtractionReviewItem;sourcePdf:string;busy:boolean;decide:(item:ExtractionReviewItem,decision:'approved'|'rejected')=>Promise<void>}) { const status = item.humanReviewStatus; return <article className={`${styles.candidateCard} ${item.scalarConflict ? styles.conflictCard : ''}`}><div className={styles.candidateTop}><div><div className={styles.candidateLabel}>{item.label}</div><div className={styles.candidateValue}>{item.formattedValue}</div></div><span className={status === 'approved' ? styles.approvedBadge : status === 'rejected' ? styles.rejectedBadge : styles.unreviewedBadge}>{status === 'approved' ? 'Approved' : status === 'rejected' ? 'Rejected' : 'Unreviewed'}</span></div><div className={styles.candidateMeta}>{item.scalarConflict && <span className={styles.attention}>Multiple scalar candidates — review required</span>}{item.confidence === null ? <span>Confidence: Not provided</span> : <span>Confidence: {item.confidence}</span>}<span>{item.evidence.length} evidence {item.evidence.length === 1 ? 'reference' : 'references'}</span></div>{item.validationIssues.length > 0 && <div className={styles.validationIssues}>{item.validationIssues.join(' · ')}</div>}<div className={styles.decisionActions} aria-label={`Review ${item.label}`}><button type="button" className={`${styles.decisionButton} ${status === 'approved' ? styles.approvedButton : ''}`} disabled={busy} onClick={()=>void decide(item,'approved')}>{busy ? 'Saving…' : status === 'approved' ? 'Approved' : 'Approve'}</button><button type="button" className={`${styles.decisionButton} ${status === 'rejected' ? styles.rejectedButton : ''}`} disabled={busy} onClick={()=>void decide(item,'rejected')}>{busy ? 'Saving…' : status === 'rejected' ? 'Rejected' : 'Reject'}</button></div>{item.decidedAt && <div className={styles.decisionTime}>Decision {item.decisionNumber} · {new Date(item.decidedAt).toLocaleString()}</div>}<details className={styles.evidenceDetails}><summary>View evidence</summary>{item.evidence.length === 0 ? <p className={styles.attention}>No evidence was attached.</p> : item.evidence.map((evidence, index) => <div className={styles.evidenceItem} key={`${item.key}:${index}`}><div><strong>Source page</strong><span>{evidence.pageNumber ?? 'Not provided'}</span></div>{evidence.sectionLabel && <div><strong>Section</strong><span>{evidence.sectionLabel}</span></div>}{evidence.snippet && <blockquote>{evidence.snippet}</blockquote>}<a href={`${sourcePdf}${evidence.pageNumber === null ? '' : `?page=${evidence.pageNumber}`}`} target="_blank" rel="noopener noreferrer">Open source PDF{evidence.pageNumber === null ? '' : ` · Page ${evidence.pageNumber}`} ↗</a><div className={styles.evidenceMeta}>Bounding box: {evidence.boundingBoxAvailable ? 'Available' : 'Not provided'} · Method: {evidence.extractionMethod}{evidence.extractionVersion ? ` (${evidence.extractionVersion})` : ''}</div></div>)}</details></article>; }
