'use client';
import { useCallback, useEffect, useState } from 'react'; import type { OpportunityDto, UnderwritingVersionDto } from '@/lib/opportunities/application/dtos'; import { createDefaultEnvelope, decimalFromDisplay, formatCurrency, formatNumber } from '@/lib/opportunities/ui/format'; import UnderwritingEditor from './UnderwritingEditor'; import styles from './opportunities.module.css';
import OpportunitySources from './OpportunitySources';
import OpportunityExtractionReview from './OpportunityExtractionReview';
import type { ExtractionReviewModel } from '@/lib/opportunities/ingestion/extraction-review';
type Api<T>={ok:boolean;data:T;error?:{kind:string;message:string}};
async function request<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{cache:'no-store',...init});const json=await response.json() as Api<T>;if(!json.ok){const error=new Error(json.error?.message||'Request failed.') as Error&{kind?:string};error.kind=json.error?.kind;throw error}return json.data}
export default function OpportunityWorkspace({opportunityId}:{opportunityId:string}){
 const [opportunity,setOpportunity]=useState<OpportunityDto|null>(null),[versions,setVersions]=useState<UnderwritingVersionDto[]>([]),[review,setReview]=useState<ExtractionReviewModel|null>(null),[reviewError,setReviewError]=useState(''),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');setReviewError('');try{const [o,v,r]=await Promise.all([request<OpportunityDto>(`/api/opportunities/${opportunityId}`),request<UnderwritingVersionDto[]>(`/api/opportunities/${opportunityId}/underwritings`),request<ExtractionReviewModel|null>(`/api/opportunities/${opportunityId}/extraction-review`).catch(c=>{setReviewError(c instanceof Error?c.message:'Extraction review could not be loaded.');return null})]);setOpportunity(o);setVersions(v);setReview(r);setSelected(current=>current&&v.some(x=>x.id===current)?current:(v.find(x=>x.active)?.id||v[0]?.id||null));}catch(c){setError(c instanceof Error?c.message:'Unable to load Opportunity.')}finally{setLoading(false)}},[opportunityId]);
 useEffect(()=>{void load();const warning=sessionStorage.getItem('opportunity-warning');if(warning){setError(warning);sessionStorage.removeItem('opportunity-warning')}},[load]);
 async function saveMetadata(form:HTMLFormElement){if(!opportunity)return;setBusy(true);try{const f=new FormData(form);const updated=await request<OpportunityDto>(`/api/opportunities/${opportunityId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:opportunity.revision,patch:{name:f.get('name'),stage:f.get('stage'),address:{market:f.get('market'),city:f.get('city'),state:f.get('state')},askingPrice:decimalFromDisplay(String(f.get('askingPrice')||'')),existingBuildingAreaSf:decimalFromDisplay(String(f.get('gla')||'')),assignedToEmail:f.get('assignedToEmail'),notes:f.get('notes')}})});setOpportunity(updated);setEditing(false)}catch(c){const x=c as Error&{kind?:string};setError(x.kind==='revision_conflict'?'This Opportunity changed elsewhere. Reload before retrying.':x.message)}finally{setBusy(false)}}
 async function createUnderwriting(){if(!opportunity)return;setBusy(true);setError('');try{const created=await request<UnderwritingVersionDto>(`/api/opportunities/${opportunityId}/underwritings`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({envelope:createDefaultEnvelope({askingPrice:opportunity.askingPrice,landAreaSf:opportunity.landAreaSf,buildingAreaSf:opportunity.existingBuildingAreaSf})})});setVersions(v=>[created,...v.map(x=>({...x,active:false}))]);setSelected(created.id)}catch(c){setError(c instanceof Error?c.message:'Underwriting could not be created.')}finally{setBusy(false)}}
 const current=versions.find(x=>x.id===selected)||null;
 if(loading)return <div className={styles.shell}><main className={styles.main}><div className={styles.muted}>Loading Opportunity…</div></main></div>;
 return <div className={styles.shell}><main className={styles.main}>{error&&<div className={`${styles.notice} ${error.includes('created, but')?styles.warning:styles.error}`}>{error} <button onClick={()=>void load()}>Reload</button></div>}{opportunity&&<><div className={styles.header}><div><h1 className={styles.title}>{opportunity.name}</h1><div className={styles.muted}>{opportunity.address.market||[opportunity.address.city,opportunity.address.state].filter(Boolean).join(', ')||'Location not set'} · Updated {new Date(opportunity.updatedAt).toLocaleString()}</div></div><button className={`${styles.button} ${styles.buttonSecondary}`} onClick={()=>setEditing(x=>!x)}>Edit metadata</button></div>
 <section className={styles.panel}><h2 className={styles.sectionTitle}>Opportunity metadata</h2>{editing?<form onSubmit={e=>{e.preventDefault();void saveMetadata(e.currentTarget)}}><div className={styles.grid}><label className={styles.field}>Name<input className={styles.input} name="name" defaultValue={opportunity.name}/></label><label className={styles.field}>Stage<select className={styles.select} name="stage" defaultValue={opportunity.stage}>{['new','screening','diligence','loi_preparation','loi_submitted','negotiation','under_contract','dead'].map(x=><option key={x}>{x}</option>)}</select></label><label className={styles.field}>Market<input className={styles.input} name="market" defaultValue={opportunity.address.market||''}/></label><label className={styles.field}>City<input className={styles.input} name="city" defaultValue={opportunity.address.city||''}/></label><label className={styles.field}>State<input className={styles.input} name="state" defaultValue={opportunity.address.state||''}/></label><label className={styles.field}>Asking price<input className={styles.input} name="askingPrice" defaultValue={opportunity.askingPrice||''}/></label><label className={styles.field}>GLA<input className={styles.input} name="gla" defaultValue={opportunity.existingBuildingAreaSf||''}/></label><label className={styles.field}>Assignee<input className={styles.input} name="assignedToEmail" defaultValue={opportunity.assignedToEmail||''}/></label><label className={styles.field}>Notes<textarea className={styles.input} name="notes" defaultValue={opportunity.notes||''}/></label></div><div className={styles.actions} style={{marginTop:14}}><button className={styles.button} disabled={busy}>Save metadata</button><button type="button" className={`${styles.button} ${styles.buttonSecondary}`} onClick={()=>setEditing(false)}>Cancel</button></div></form>:<div className={styles.grid}><Meta label="Stage" value={opportunity.stage}/><Meta label="Asking price" value={formatCurrency(opportunity.askingPrice)}/><Meta label="GLA" value={formatNumber(opportunity.existingBuildingAreaSf,' SF')}/><Meta label="Assignee" value={opportunity.assignedToEmail||'—'}/><Meta label="Created" value={new Date(opportunity.createdAt).toLocaleDateString()}/></div>}</section><OpportunitySources opportunityId={opportunityId}/><OpportunityExtractionReview review={review} loading={loading} error={reviewError}/>
 <div className={styles.header}><div><h2 className={styles.sectionTitle}>Underwriting</h2>{versions.length>0&&<select aria-label="Underwriting version" className={styles.select} value={selected||''} onChange={e=>setSelected(e.target.value)}>{versions.map(v=><option key={v.id} value={v.id}>Version {v.versionNumber} · {v.status}{v.active?' · Active':''}</option>)}</select>}</div>{versions.length===0&&<button className={styles.button} disabled={busy} onClick={()=>void createUnderwriting()}>{busy?'Creating…':'Create Underwriting'}</button>}</div>
 {versions.length===0?<div className={styles.panel}><h3>No underwriting versions</h3><p className={styles.muted}>Create a retail-development draft to begin screening this Opportunity.</p></div>:current&&<UnderwritingEditor key={current.id} opportunityId={opportunityId} askingPrice={opportunity.askingPrice} version={current} onChanged={updated=>{setVersions(v=>v.map(x=>x.id===updated.id?updated:x));setSelected(updated.id)}} onCloned={cloned=>{setVersions(v=>[cloned,...v.map(x=>({...x,active:false}))]);setSelected(cloned.id)}}/>}</>}</main></div>;
}
function Meta({label,value}:{label:string;value:string}){return <div><div className={styles.metricLabel}>{label}</div><div>{value}</div></div>}
