'use client';
import type { ExtractionReviewModel, ExtractionReviewItem } from '@/lib/opportunities/ingestion/extraction-review';
import styles from './OpportunityExtractionReview.module.css';
export default function OpportunityExtractionReview({ review, loading, error }:{ review: ExtractionReviewModel | null; loading: boolean; error: string }) {
  if (loading) return <section className={styles.panel} aria-busy="true"><p className={styles.muted}>Loading extraction review…</p></section>;
  if (error) return <section className={styles.panel}><h2 className={styles.sectionTitle}>Extraction review</h2><p className={styles.reviewError}>{error}</p></section>;
  if (!review) return <section className={styles.panel}><h2 className={styles.sectionTitle}>Extraction review</h2><p className={styles.muted}>No successful extraction is available for review.</p></section>;
  return <section className={`${styles.panel} ${styles.reviewPanel}`} aria-labelledby="extraction-review-title"><div className={styles.reviewHeader}><div><div className={styles.eyebrow}>Extraction review</div><h2 id="extraction-review-title" className={styles.reviewTitle}>{review.factCount} facts extracted</h2><p className={styles.muted}>Extraction completed successfully · Attempt {review.attemptNumber}</p></div><span className={styles.unreviewedBadge}>Awaiting human review</span></div><div className={styles.reviewSummary}><Summary value={String(review.factCount)} label="Facts extracted"/><Summary value={`${review.representedDestinationCount} of ${review.registryDestinationCount}`} label="Registry destinations"/><Summary value={String(review.missingDestinationCount)} label="Fields not found"/><Summary value={review.decisionCount === 0 ? 'Unreviewed' : `${review.decisionCount} reviewed`} label="Human review"/></div><div className={styles.machineNote}><strong>Machine validation passed.</strong> These extracted facts have not been human-approved.</div>{review.groups.map(group => <div className={styles.reviewGroup} key={group.key}><h3>{group.label}</h3><div className={styles.reviewItems}>{group.items.map(item => <CandidateCard item={item} key={item.key}/>)}</div></div>)}<details className={styles.missingSection}><summary>No candidate extracted ({review.missingDestinationCount})</summary><p className={styles.muted}>These fields were not represented in this extraction. Their absence is not a negative factual assertion.</p><div className={styles.missingGrid}>{review.missingDestinations.map(item => <div key={item.fieldPath}><strong>{item.label}</strong><span>No candidate extracted</span></div>)}</div></details></section>;
}
function Summary({value,label}:{value:string;label:string}) { return <div><strong>{value}</strong><span>{label}</span></div>; }
function CandidateCard({item}:{item:ExtractionReviewItem}) { return <article className={`${styles.candidateCard} ${item.scalarConflict ? styles.conflictCard : ''}`}><div className={styles.candidateTop}><div><div className={styles.candidateLabel}>{item.label}</div><div className={styles.candidateValue}>{item.formattedValue}</div></div><span className={styles.unreviewedBadge}>{item.humanReviewStatus === 'reviewed' ? 'Reviewed' : 'Unreviewed'}</span></div><div className={styles.candidateMeta}>{item.scalarConflict && <span className={styles.attention}>Multiple scalar candidates — review required</span>}{item.confidence === null ? <span>Confidence: Not provided</span> : <span>Confidence: {item.confidence}</span>}<span>{item.evidence.length} evidence {item.evidence.length === 1 ? 'reference' : 'references'}</span></div>{item.validationIssues.length > 0 && <div className={styles.validationIssues}>{item.validationIssues.join(' · ')}</div>}<details className={styles.evidenceDetails}><summary>View evidence</summary>{item.evidence.length === 0 ? <p className={styles.attention}>No evidence was attached.</p> : item.evidence.map((evidence, index) => <div className={styles.evidenceItem} key={`${item.key}:${index}`}><div><strong>Source page</strong><span>{evidence.pageNumber ?? 'Not provided'}</span></div>{evidence.sectionLabel && <div><strong>Section</strong><span>{evidence.sectionLabel}</span></div>}{evidence.snippet && <blockquote>{evidence.snippet}</blockquote>}<div className={styles.evidenceMeta}>Bounding box: {evidence.boundingBoxAvailable ? 'Available' : 'Not provided'} · Method: {evidence.extractionMethod}{evidence.extractionVersion ? ` (${evidence.extractionVersion})` : ''}</div></div>)}</details></article>; }
