'use client';
import Link from 'next/link'; import { useRouter, useSearchParams } from 'next/navigation'; import { useEffect, useState } from 'react';
import type { OpportunityDto } from '@/lib/opportunities/application/dtos'; import { formatCurrency, formatNumber, formatPercent } from '@/lib/opportunities/ui/format'; import styles from './opportunities.module.css';
import { ScreenBadge } from './presentation';
type Payload = { items: OpportunityDto[]; page: number; pageSize: number; total: number };
export default function OpportunityListClient() {
 const router=useRouter(), search=useSearchParams(); const [data,setData]=useState<Payload|null>(null); const [error,setError]=useState('');
 useEffect(()=>{ let live=true; fetch(`/api/opportunities?${search.toString()}`,{cache:'no-store'}).then(r=>r.json()).then(j=>{if(!live)return;if(j.ok)setData(j.data);else setError(j.error?.message||'Unable to load Opportunities.');}).catch(()=>setError('Unable to load Opportunities.'));return()=>{live=false};},[search]);
 const set=(name:string,value:string)=>{const q=new URLSearchParams(search.toString());if(value)q.set(name,value);else q.delete(name);q.delete('page');router.push(`/admin/opportunities?${q}`)};
 return <div className={styles.shell}><main className={styles.main}><div className={styles.header}><div><h1 className={styles.title}>Opportunities</h1><div className={styles.muted}>Acquisition screening workspace</div></div><Link className={styles.button} href="/admin/opportunities/new">+ New Opportunity</Link></div>
 <div className={styles.toolbar}><select aria-label="Stage" className={styles.select} value={search.get('stage')||''} onChange={e=>set('stage',e.target.value)}><option value="">All stages</option>{['new','screening','diligence','loi_preparation','loi_submitted','negotiation','under_contract','dead'].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Screen result" className={styles.select} value={search.get('screenResult')||''} onChange={e=>set('screenResult',e.target.value)}><option value="">All screens</option><option>PURSUE</option><option>REVIEW</option><option>PASS</option></select><input aria-label="Market" className={styles.input} placeholder="Market" defaultValue={search.get('market')||''} onBlur={e=>set('market',e.target.value)}/><select aria-label="Promotion status" className={styles.select} value={search.get('promoted')||''} onChange={e=>set('promoted',e.target.value)}><option value="">Any promotion status</option><option value="false">Not promoted</option><option value="true">Promoted</option></select></div>
 {error&&<div className={`${styles.notice} ${styles.error}`}>{error} <button onClick={()=>location.reload()}>Retry</button></div>}{!data&&!error&&<div className={styles.muted}>Loading Opportunities…</div>}{data?.items.length===0&&<div className={styles.panel}><h2>No Opportunities yet</h2><p className={styles.muted}>Create the first early-look acquisition screen. This will not create a Deal.</p><Link className={styles.button} href="/admin/opportunities/new">New Opportunity</Link></div>}
 {data&&data.items.length>0&&<div className={`${styles.panel} ${styles.tableWrap}`}><table className={styles.table}><thead><tr><th>Name</th><th>Market / location</th><th>Stage</th><th>Asking price</th><th>GLA</th><th>Screen</th><th>ROC</th><th>Spread</th><th>Updated</th></tr></thead><tbody>{data.items.map(o=><tr key={o.id} data-clickable="true" tabIndex={0} onClick={()=>router.push(`/admin/opportunities/${o.id}`)} onKeyDown={e=>e.key==='Enter'&&router.push(`/admin/opportunities/${o.id}`)}><td><strong>{o.name}</strong></td><td>{o.address.market||[o.address.city,o.address.state].filter(Boolean).join(', ')||'—'}</td><td>{o.stage}</td><td>{formatCurrency(o.askingPrice)}</td><td>{formatNumber(o.activeUnderwriting?.buildingAreaSf??o.existingBuildingAreaSf,' SF')}</td><td><ScreenBadge value={o.activeUnderwriting?.screenResult}/></td><td>{formatPercent(o.activeUnderwriting?.returnOnCost)}</td><td>{formatPercent(o.activeUnderwriting?.developmentSpread)}</td><td>{new Date(o.updatedAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>}
 {data&&<div className={styles.actions}><button className={`${styles.button} ${styles.buttonSecondary}`} disabled={data.page<=1} onClick={()=>set('page',String(data.page-1))}>Previous</button><span className={styles.muted}>Page {data.page} · {data.total} total</span><button className={`${styles.button} ${styles.buttonSecondary}`} disabled={data.page*data.pageSize>=data.total} onClick={()=>set('page',String(data.page+1))}>Next</button></div>}</main></div>;
}
