'use client';
import { useEffect, useState } from 'react';
import styles from './OpportunityExtractionReview.module.css';
type Api<T>={ok:boolean;data:T;error?:{kind:string;message:string}};
type State={stage:'not_ready'|'ready'|'extracting'|'failed'|'succeeded';attemptNumber:number|null;canRetry:boolean};
export default function OpportunityExtractionControl({opportunityId,active}:{opportunityId:string;active:boolean}){
  const[state,setState]=useState<State|null>(null);const[running,setRunning]=useState(false);const[message,setMessage]=useState('');
  useEffect(()=>{if(active)void load(opportunityId).then(setState).catch(cause=>setMessage(cause instanceof Error?cause.message:'Extraction state could not be loaded.'))},[active,opportunityId]);
  if(!active)return null;
  async function extract(){if(running||!state||!['ready','failed'].includes(state.stage))return;setRunning(true);setMessage('');const key=`upperline:extraction-retry:${opportunityId}`;try{const retryCommandId=state.stage==='failed'?stableRetryCommand(key):undefined;const response=await fetch(`/api/opportunities/${opportunityId}/extraction-control`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(retryCommandId?{retryCommandId}:{})});const json=await response.json() as Api<unknown>;if(!json.ok)throw new Error(json.error?.message??'Extraction failed.');localStorage.removeItem(key);window.location.reload()}catch(cause){try{const durable=await load(opportunityId);setState(durable);if(durable.stage==='failed')localStorage.removeItem(key)}catch{/* retain retry identity while authoritative state is unknown */}setMessage(cause instanceof Error?cause.message:'Extraction failed.')}finally{setRunning(false)}}
  return <section className={styles.panel}><h2 className={styles.sectionTitle}>Document extraction</h2>{!state?<p className={styles.muted}>Loading extraction state…</p>:state.stage==='not_ready'?<p className={styles.muted}>A verified PDF is required before extraction.</p>:state.stage==='extracting'?<p className={styles.muted}>Extracting… Attempt {state.attemptNumber}</p>:state.stage==='succeeded'?<p className={styles.muted}>Extraction succeeded. Refreshing candidate review…</p>:<><p className={state.stage==='failed'?styles.reviewError:styles.muted}>{state.stage==='failed'?'Extraction failed':'Verified PDF is ready for extraction.'}</p><button type="button" className={styles.decisionButton} disabled={running||(!state.canRetry&&state.stage==='failed')} onClick={()=>void extract()}>{running?'Extracting…':state.stage==='failed'?'Retry Extraction':'Run Extraction'}</button></>}{message&&<p className={styles.reviewError} role="alert">{message}</p>}</section>
}
async function load(opportunityId:string){const response=await fetch(`/api/opportunities/${opportunityId}/extraction-control`,{cache:'no-store'});const json=await response.json() as Api<State>;if(!json.ok)throw new Error(json.error?.message??'Extraction state could not be loaded.');return json.data}
function stableRetryCommand(key:string){const current=localStorage.getItem(key);if(current&&/^[0-9a-f-]{36}$/.test(current))return current;const created=crypto.randomUUID();localStorage.setItem(key,created);return created}
