import { describe, expect, it } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs'; import { join } from 'node:path';
const root=process.cwd();
describe('candidate decision application boundary', () => {
  it('exposes one authenticated PUT route and no caller-controlled authority', () => { const route=readFileSync(join(root,'src/app/api/opportunities/[id]/extraction-review/candidates/[candidateId]/decision/route.ts'),'utf8'); expect(route).toContain('export async function PUT'); expect(route).not.toMatch(/export async function (?:POST|PATCH|DELETE)/); expect(route).toContain('authenticatedOpportunityEndpoint'); expect(route).toContain('reviewerEmail: actor.email'); expect(route).not.toMatch(/SUPABASE_SERVICE_ROLE_KEY|acceptedValue|edited_and_accepted/); });
  it('uses one established dynamic slug name beneath the Opportunity API root', () => { const directories=readdirSync(join(root,'src/app/api/opportunities'),{withFileTypes:true}).filter(entry=>entry.isDirectory()&&/^\[[^\]]+\]$/.test(entry.name)).map(entry=>entry.name).sort(); expect(directories).toEqual(['[id]']); });
  it('keeps RPC, reviewer identity, and persistence authority out of the client', () => { const client=readFileSync(join(root,'src/components/opportunities/OpportunityExtractionReview.tsx'),'utf8'); expect(client).not.toMatch(/record_opportunity_candidate_fact_decision|reviewerEmail|service_role|acceptedValue|edited_and_accepted/); expect(client).not.toMatch(/POST|PATCH|DELETE/); expect(client).toContain("method: 'PUT'"); expect(client).not.toMatch(/dangerouslySetInnerHTML|innerHTML/); });
  it('uses authoritative responses, blocks per-candidate duplicates, and reconciles conflicts', () => { const client=readFileSync(join(root,'src/components/opportunities/OpportunityExtractionReview.tsx'),'utf8'); expect(client).toContain('if (pending.has(item.candidateId)) return'); expect(client).toContain('disabled={busy}'); expect(client).toContain('if (response.status === 409)'); expect(client).toContain('await refresh(true)'); expect(client).toContain('setSelection(json.data)'); expect(client).not.toMatch(/humanReviewStatus\s*:/); });
  it('keeps the repository server-only and uses only the reviewed RPC', () => { const repository=readFileSync(join(root,'src/lib/opportunities/ingestion/supabase-candidate-decision-repository.ts'),'utf8'); expect(repository).toContain("import 'server-only'"); expect(repository).toContain("rpc('record_opportunity_candidate_fact_decision'"); expect(repository).not.toMatch(/\.from\([^)]*\)\.(?:insert|update|delete|upsert)/); });
});
