import { createHash } from 'node:crypto';
import { describe, expect, it, vi } from 'vitest';
vi.mock('server-only', () => ({}));
import { opportunityError } from '../application/errors';
import type { ExtractionRepositoryPort, ExtractionRunRecord, VerifiedExtractionArtifact } from './extraction-contracts';
import { getExtractionControlState, PRODUCTION_EXTRACTION_CONFIGURATION, runExtractionControl } from './extraction-control';

const actor={email:'reviewer@upperlineco.com',name:'Reviewer'};const opportunityId='11111111-1111-4111-8111-111111111111';const bytes=new Uint8Array([1,2,3]);
const artifact:VerifiedExtractionArtifact={opportunityId,ingestionId:'22222222-2222-4222-8222-222222222222',artifactId:'33333333-3333-4333-8333-333333333333',storagePath:'server/private',sha256Digest:createHash('sha256').update(bytes).digest('hex'),byteSize:3,pageCount:1,detectedMediaType:'application/pdf'};
class Repository implements ExtractionRepositoryPort {run:ExtractionRunRecord|null=null;artifact:VerifiedExtractionArtifact|null=artifact;failed=0;lastLogicalKey='';async resolveEligibleArtifact(){return this.artifact}async getLatestRun(_artifact:VerifiedExtractionArtifact,logicalKey:string){this.lastLogicalKey=logicalKey;return this.run}async allocateRun(input:Parameters<ExtractionRepositoryPort['allocateRun']>[0]){if(this.run)return{run:this.run,disposition:'recovered' as const};this.run={runId:input.runId,attemptNumber:1,status:'running'};return{run:this.run,disposition:'allocated' as const}}async allocateRetryRun(input:Parameters<ExtractionRepositoryPort['allocateRetryRun']>[0]){if(this.run?.status!=='failed')throw opportunityError('extraction_retry_not_allowed','Retry denied.');this.run={runId:input.runId,attemptNumber:this.run.attemptNumber+1,status:'running'};return{run:this.run,disposition:'allocated' as const}}async completeRun(input:Parameters<ExtractionRepositoryPort['completeRun']>[0]){this.run={runId:input.runId,attemptNumber:this.run?.attemptNumber??1,status:'succeeded',candidateCount:input.candidates.length,evidenceCount:0};return this.run}async failRun(){this.failed++;if(this.run)this.run.status='failed'}async recoverSucceededRun(){return this.run!}}
function dependencies(repository=new Repository(),provider=vi.fn(async()=>({schemaVersion:'land-flyer-v2',assertions:[],propositions:[]}))){return{repository,authorizer:{authorize:vi.fn(async()=>undefined)},objectStore:{openExactObject:vi.fn(async()=>({metadata:{byteSize:3,mediaType:'application/pdf' as const,lastModifiedAt:null},bytes:(async function*(){yield bytes})()})),createExactUploadAuthorization:vi.fn(),inspectExactObject:vi.fn(),createExactReadAccess:vi.fn(),deleteExactUntrustedObject:vi.fn()},provider:{identifier:'openai',extract:provider},configuration:PRODUCTION_EXTRACTION_CONFIGURATION,loadCredential:():string|undefined=> 'configured',idFactory:()=> '44444444-4444-4444-8444-444444444444'}}
describe('production extraction control',()=>{
  it.each(['unauthorized','forbidden'] as const)('denies %s actors before reading state',async kind=>{const repository=new Repository();repository.resolveEligibleArtifact=vi.fn();const authorizer={authorize:vi.fn(async()=>{throw opportunityError(kind,'Denied.')})};await expect(getExtractionControlState(opportunityId,actor,{authorizer,repository})).rejects.toMatchObject({kind});expect(repository.resolveEligibleArtifact).not.toHaveBeenCalled()});
  it('projects verified, running, failed, and succeeded durable states',async()=>{const repository=new Repository();const authorizer={authorize:vi.fn(async()=>undefined)};await expect(getExtractionControlState(opportunityId,actor,{authorizer,repository})).resolves.toMatchObject({stage:'ready'});repository.run={runId:'run',attemptNumber:1,status:'running'};await expect(getExtractionControlState(opportunityId,actor,{authorizer,repository})).resolves.toMatchObject({stage:'extracting'});repository.run.status='failed';await expect(getExtractionControlState(opportunityId,actor,{authorizer,repository})).resolves.toMatchObject({stage:'failed',canRetry:true});repository.run.status='succeeded';await expect(getExtractionControlState(opportunityId,actor,{authorizer,repository})).resolves.toMatchObject({stage:'succeeded'})});
  it('queries only the server-configured logical lineage and exposes its safe contract label',async()=>{const repository=new Repository();const authorizer={authorize:vi.fn(async()=>undefined)};await expect(getExtractionControlState(opportunityId,actor,{authorizer,repository})).resolves.toMatchObject({stage:'ready',schemaVersion:'land-flyer-v2',extractionVersion:'openai-land-flyer-v2'});expect(repository.lastLogicalKey).toMatch(/^extract:[0-9a-f]{64}$/);});
  it('returns not ready and never invokes a provider without a verified artifact',async()=>{const d=dependencies();d.repository.artifact=null;await expect(getExtractionControlState(opportunityId,actor,d)).resolves.toMatchObject({stage:'not_ready'});await expect(runExtractionControl(opportunityId,actor,{},d)).rejects.toMatchObject({kind:'artifact_not_ready'});expect(d.provider.extract).not.toHaveBeenCalled()});
  it('extracts a verified artifact and makes a succeeded replay cost-free',async()=>{const d=dependencies();await expect(runExtractionControl(opportunityId,actor,{},d)).resolves.toMatchObject({run:{status:'succeeded'}});expect(d.provider.extract).toHaveBeenCalledOnce();await expect(runExtractionControl(opportunityId,actor,{},d)).resolves.toMatchObject({disposition:'recovered',run:{status:'succeeded'}});expect(d.provider.extract).toHaveBeenCalledOnce()});
  it('fails closed before allocation when the server credential is absent',async()=>{const d=dependencies();d.loadCredential=()=>undefined;d.repository.allocateRun=vi.fn(d.repository.allocateRun.bind(d.repository));await expect(runExtractionControl(opportunityId,actor,{},d)).rejects.toMatchObject({kind:'provider_failure',message:'The extraction provider is unavailable.'});expect(d.repository.allocateRun).not.toHaveBeenCalled();expect(d.provider.extract).not.toHaveBeenCalled()});
  it.each([{artifactId:'55555555-5555-4555-8555-555555555555'},{storagePath:'attacker/path'},{model:'attacker'}])('rejects browser authority %#',async body=>{const d=dependencies();await expect(runExtractionControl(opportunityId,actor,body,d)).rejects.toMatchObject({kind:'validation'});expect(d.authorizer.authorize).not.toHaveBeenCalled();expect(d.provider.extract).not.toHaveBeenCalled()});
  it('rejects a mismatched valid Opportunity relationship',async()=>{const d=dependencies();d.repository.artifact={...artifact,opportunityId:'66666666-6666-4666-8666-666666666666'};await expect(runExtractionControl(opportunityId,actor,{},d)).rejects.toMatchObject({kind:'integrity_conflict'});expect(d.provider.extract).not.toHaveBeenCalled()});
  it('persists a recoverable failed state without automatic retry',async()=>{const provider=vi.fn(async()=>{throw new Error('private provider detail')});const d=dependencies(new Repository(),provider);await expect(runExtractionControl(opportunityId,actor,{},d)).rejects.toMatchObject({kind:'provider_failure'});expect(d.repository.failed).toBe(1);expect(d.repository.run?.status).toBe('failed');expect(provider).toHaveBeenCalledOnce()});
});
