import { LAND_FLYER_SOURCE_DESTINATIONS, type LandFlyerSourceFieldPath } from './destination-registry';
import type { CandidateUnit, CandidateValueType, CandidateValidationState } from './contracts';
import { isTrafficCountProposition, isTrafficCountPropositionV2, type TrafficCountProposition, type TrafficCountPropositionV1, type TrafficCountPropositionV2 } from './rich-candidate';
export type ExtractionReviewEvidence = { pageNumber: number | null; snippet: string | null; sectionLabel: string | null; boundingBoxAvailable: boolean; extractionMethod: string; extractionVersion: string | null };
export type ExtractionReviewDecision = { state: 'approved' | 'rejected'; decisionNumber: number; decidedAt: string };
export type ExtractionReviewCandidate = { id: string; fieldPath: string; valueType: CandidateValueType; value: unknown; unit: CandidateUnit | null; groupKey?: string | null; assertionBasis: string; confidence: string | null; validationState: CandidateValidationState; validationIssues: string[]; ordinal: number; fingerprint: string; latestDecision: ExtractionReviewDecision | null; evidence: ExtractionReviewEvidence[] };
export type ReviewGroupKey = 'property' | 'pricing' | 'location_access' | 'site' | 'broker' | 'marketing' | 'other';
export type ExtractionReviewItem = Omit<ExtractionReviewCandidate, 'id' | 'fingerprint' | 'latestDecision'> & { key: string; candidateId: string; propositionDetails?: Record<string,string>;
  label: string; formattedValue: string; group: ReviewGroupKey; cardinality: 'scalar' | 'set'; scalarConflict: boolean;
  humanReviewStatus: 'unreviewed' | 'approved' | 'rejected'; decisionNumber: number; decidedAt: string | null };
export type ExtractionReviewModel = { attemptNumber: number; completedAt: string | null; extractionVersion: string; schemaVersion: string; factCount: number; representedDestinationCount: number; registryDestinationCount: number; missingDestinationCount: number; unreviewedCount: number; approvedCount: number; rejectedCount: number; groups: Array<{ key: ReviewGroupKey; label: string; items: ExtractionReviewItem[] }>; missingDestinations: Array<{ fieldPath: string; label: string; group: ReviewGroupKey }> };
export type ExtractionReviewSelection = { current: ExtractionReviewModel | null; historical: ExtractionReviewModel[] };
const P: Record<string, { label: string; group: ReviewGroupKey }> = {
  'document.title': { label: 'Document Title', group: 'property' }, 'property.marketedType': { label: 'Marketed Type', group: 'property' }, 'land.areaAcres': { label: 'Site Area', group: 'property' }, 'land.areaSf': { label: 'Land Area', group: 'property' }, 'tract.divisible': { label: 'Divisible', group: 'property' }, 'tract.minimumAreaAcres': { label: 'Minimum Tract Area', group: 'property' },
  'pricing.askingPrice': { label: 'Asking Price', group: 'pricing' }, 'pricing.askingPricePerLandSf': { label: 'Asking Price / Land SF', group: 'pricing' },
  'location.intersection': { label: 'Intersection', group: 'location_access' }, 'access.roadName': { label: 'Road Name', group: 'location_access' }, 'access.frontageFeet': { label: 'Frontage', group: 'location_access' }, 'access.pointDescription': { label: 'Access', group: 'location_access' }, 'access.signalizedIntersectionClaim': { label: 'Signalized Intersection', group: 'location_access' }, 'traffic.vehiclesPerDay': { label: 'Traffic Count', group: 'location_access' },
  'site.zoning': { label: 'Zoning', group: 'site' }, 'site.utilities': { label: 'Utilities', group: 'site' }, 'site.detentionClaim': { label: 'Detention', group: 'site' }, 'site.floodplainClaim': { label: 'Floodplain', group: 'site' }, 'site.wetlandsClaim': { label: 'Wetlands', group: 'site' }, 'site.easementClaim': { label: 'Easements', group: 'site' }, 'site.pipelineClaim': { label: 'Pipeline', group: 'site' }, 'site.wellClaim': { label: 'Well', group: 'site' }, 'site.cityLimitStatus': { label: 'City Limits', group: 'site' }, 'site.etjStatus': { label: 'ETJ', group: 'site' }, 'site.municipalDistrict': { label: 'Municipal District', group: 'site' }, 'site.tirz': { label: 'TIRZ', group: 'site' },
  'broker.brokerage': { label: 'Brokerage', group: 'broker' }, 'broker.contactName': { label: 'Broker Contact', group: 'broker' }, 'broker.phone': { label: 'Broker Phone', group: 'broker' }, 'broker.email': { label: 'Broker Email', group: 'broker' }, 'marketing.suggestedUse': { label: 'Suggested Use', group: 'marketing' },
};
const GROUPS: Array<{ key: ReviewGroupKey; label: string }> = [{ key: 'property', label: 'Property' }, { key: 'pricing', label: 'Pricing' }, { key: 'location_access', label: 'Location & Access' }, { key: 'site', label: 'Site' }, { key: 'broker', label: 'Broker' }, { key: 'marketing', label: 'Marketing / Use' }, { key: 'other', label: 'Other' }];
export function buildExtractionReviewModel(input: { attemptNumber: number; completedAt: string | null; extractionVersion?: string; schemaVersion?: string; candidates: ExtractionReviewCandidate[] }): ExtractionReviewModel {
  const represented = new Set(input.candidates.map(c => c.fieldPath)); const counts = new Map<string, number>(); for (const c of input.candidates) counts.set(c.fieldPath, (counts.get(c.fieldPath) ?? 0) + 1);
  const items: ExtractionReviewItem[] = input.candidates.map(c => { const definition = LAND_FLYER_SOURCE_DESTINATIONS[c.fieldPath as LandFlyerSourceFieldPath]; const presentation = presentationFor(c.fieldPath); const cardinality = c.groupKey==='traffic_count:1'||c.groupKey==='traffic_count:2' ? 'set' : definition?.cardinality ?? 'scalar'; const { id, fingerprint: _fingerprint, latestDecision, ...publicCandidate } = c; void _fingerprint; const rich=isTrafficCountPropositionV2(c.value)?trafficPresentationV2(c.value):isTrafficCountProposition(c.value)?trafficPresentation(c.value):null; return { ...publicCandidate, candidateId: id, key: `${c.fieldPath}:${c.ordinal}`, ...presentation, formattedValue: rich?.formattedValue??formatCandidateValue(c.valueType, c.value, c.unit), ...(rich?{propositionDetails:rich.details}:{}), cardinality, scalarConflict: cardinality === 'scalar' && (counts.get(c.fieldPath) ?? 0) > 1, humanReviewStatus: latestDecision?.state ?? 'unreviewed', decisionNumber: latestDecision?.decisionNumber ?? 0, decidedAt: latestDecision?.decidedAt ?? null }; });
  const groups = GROUPS.map(group => ({ ...group, items: items.filter(item => item.group === group.key).sort((a, b) => a.ordinal - b.ordinal) })).filter(group => group.items.length > 0);
  const missingDestinations = Object.keys(LAND_FLYER_SOURCE_DESTINATIONS).filter(path => !represented.has(path)).map(fieldPath => ({ fieldPath, ...presentationFor(fieldPath) }));
  return { attemptNumber: input.attemptNumber, completedAt: input.completedAt, extractionVersion: input.extractionVersion ?? 'unknown', schemaVersion: input.schemaVersion ?? 'unknown', factCount: input.candidates.length, representedDestinationCount: represented.size, registryDestinationCount: Object.keys(LAND_FLYER_SOURCE_DESTINATIONS).length, missingDestinationCount: missingDestinations.length, unreviewedCount: items.filter(item => item.humanReviewStatus === 'unreviewed').length, approvedCount: items.filter(item => item.humanReviewStatus === 'approved').length, rejectedCount: items.filter(item => item.humanReviewStatus === 'rejected').length, groups, missingDestinations };
}
function trafficPresentation(p:TrafficCountPropositionV1){const time=p.measurementTime; const vintage=time.precision==='unknown'?'Unknown':time.precision==='year'?String(time.year):time.precision==='month'?`${time.year}-${String(time.month).padStart(2,'0')}`:`${time.year}-${String(time.month).padStart(2,'0')}-${String(time.day).padStart(2,'0')}`; const basis=p.basis.normalized==='unknown'?`Unknown${p.basis.sourceLiteral?` · Source: ${p.basis.sourceLiteral}`:''}`:`${p.basis.normalized} · Source: ${p.basis.sourceLiteral}`; const roadway=p.roadway?.sourceLiteral??'Not reported'; const location=p.countLocation??'Not reported'; const direction=p.direction??'Not reported'; return {formattedValue:`${grouped(String(p.count))} ${p.basis.normalized==='unknown'?'vehicles/day':p.basis.normalized} · Roadway: ${roadway} · Measurement: ${vintage} · Location: ${location} · Direction: ${direction}`,details:{basis,roadway,vintage,location,direction}};}
function trafficPresentationV2(p:TrafficCountPropositionV2){const vintage=trafficVintage(p);const roadway=p.roadway.sourceLiteral;const crossStreet=p.crossStreet?.sourceLiteral??'Not reported';const offset=p.crossStreetOffset.distance===null?'Not reported':`${p.crossStreetOffset.distance.toFixed(2)} mi${p.crossStreetOffset.direction?` ${p.crossStreetOffset.direction}`:''}`;const subjectDistance=p.sourceRelativeSubjectDistance.distance===null?'Not reported':`${p.sourceRelativeSubjectDistance.distance.toFixed(2)} mi`;const volumeType=p.sourceVolumeType??'Not reported';const heading=p.basis.sourceLiteral??'Not reported';const at=p.crossStreet?`${roadway} @ ${crossStreet}`:`${roadway} · Cross street: Not reported`;return{formattedValue:`${grouped(String(p.count))} vehicles/day · ${at} · Cross-street offset: ${offset} · Measurement: ${vintage} · Source heading: ${heading} · Volume type: ${volumeType} · Reported distance from subject: ${subjectDistance}`,details:{basis:p.basis.normalized,sourceHeading:heading,volumeType,roadway,crossStreet,crossStreetOffset:offset,measurement:vintage,sourceRelativeSubjectDistance:subjectDistance}};}
function trafficVintage(p:TrafficCountProposition){const time=p.measurementTime;return time.precision==='unknown'?'Unknown':time.precision==='year'?String(time.year):time.precision==='month'?`${time.year}-${String(time.month).padStart(2,'0')}`:`${time.year}-${String(time.month).padStart(2,'0')}-${String(time.day).padStart(2,'0')}`;}
function presentationFor(fieldPath: string) { return P[fieldPath] ?? { label: (fieldPath.split('.').at(-1) ?? fieldPath).replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/^./, c => c.toUpperCase()), group: 'other' as const }; }
function numeric(value: unknown) { return typeof value === 'string' && /^-?(?:0|[1-9]\d*)(?:\.\d+)?$/.test(value) ? value : null; }
function grouped(value: string) { const negative = value.startsWith('-'); const unsigned = negative ? value.slice(1) : value; const [whole, fraction] = unsigned.split('.'); const result = whole.replace(/\B(?=(\d{3})+(?!\d))/g, ','); return `${negative ? '-' : ''}${result}${fraction === undefined ? '' : `.${fraction}`}`; }
export function formatCandidateValue(type: CandidateValueType, value: unknown, unit: CandidateUnit | null): string {
  if (type === 'boolean') return value === true ? 'Yes' : value === false ? 'No' : 'Not provided'; if (value === null || value === undefined || value === '') return 'Not provided'; if (type === 'json') return JSON.stringify(value); const text = String(value); const number = numeric(text);
  if ((type === 'decimal' || type === 'integer') && number !== null) { const formatted = grouped(number); if (unit === 'USD') return `${number.startsWith('-') ? '-$' : '$'}${grouped(number.replace(/^-/, ''))}`; if (unit === 'USD_PER_LAND_SF') { const [whole, fraction = ''] = grouped(number).split('.'); return `${whole.startsWith('-') ? '-$' + whole.slice(1) : '$' + whole}.${fraction.padEnd(2, '0')} / SF`; } const suffix: Partial<Record<CandidateUnit, string>> = { ACRES: ' acres', SF: ' SF', FEET: ' ft', VEHICLES_PER_DAY: ' vehicles/day', MONTHS: ' months', DAYS: ' days', COUNT: '' }; return `${formatted}${suffix[unit ?? 'NONE'] ?? ''}`; } return text;
}
