import { LAND_FLYER_SOURCE_DESTINATIONS, type LandFlyerSourceFieldPath } from './destination-registry';
import type { CandidateUnit, CandidateValueType, CandidateValidationState } from './contracts';
export type ExtractionReviewEvidence = { pageNumber: number | null; snippet: string | null; sectionLabel: string | null; boundingBoxAvailable: boolean; extractionMethod: string; extractionVersion: string | null };
export type ExtractionReviewCandidate = { id: string; fieldPath: string; valueType: CandidateValueType; value: unknown; unit: CandidateUnit | null; assertionBasis: string; confidence: string | null; validationState: CandidateValidationState; validationIssues: string[]; ordinal: number; fingerprint: string; decisionCount: number; evidence: ExtractionReviewEvidence[] };
export type ReviewGroupKey = 'property' | 'pricing' | 'location_access' | 'site' | 'broker' | 'marketing' | 'other';
export type ExtractionReviewItem = Omit<ExtractionReviewCandidate, 'id' | 'fingerprint'> & { key: string;
  label: string; formattedValue: string; group: ReviewGroupKey; cardinality: 'scalar' | 'set';
  scalarConflict: boolean; humanReviewStatus: 'unreviewed' | 'reviewed' };
export type ExtractionReviewModel = { attemptNumber: number; completedAt: string | null; factCount: number; representedDestinationCount: number; registryDestinationCount: number; missingDestinationCount: number; decisionCount: number; groups: Array<{ key: ReviewGroupKey; label: string; items: ExtractionReviewItem[] }>; missingDestinations: Array<{ fieldPath: string; label: string; group: ReviewGroupKey }> };
const P: Record<string, { label: string; group: ReviewGroupKey }> = {
  'document.title': { label: 'Document Title', group: 'property' }, 'property.marketedType': { label: 'Marketed Type', group: 'property' }, 'land.areaAcres': { label: 'Site Area', group: 'property' }, 'land.areaSf': { label: 'Land Area', group: 'property' }, 'tract.divisible': { label: 'Divisible', group: 'property' }, 'tract.minimumAreaAcres': { label: 'Minimum Tract Area', group: 'property' },
  'pricing.askingPrice': { label: 'Asking Price', group: 'pricing' }, 'pricing.askingPricePerLandSf': { label: 'Asking Price / Land SF', group: 'pricing' },
  'location.intersection': { label: 'Intersection', group: 'location_access' }, 'access.roadName': { label: 'Road Name', group: 'location_access' }, 'access.frontageFeet': { label: 'Frontage', group: 'location_access' }, 'access.pointDescription': { label: 'Access', group: 'location_access' }, 'access.signalizedIntersectionClaim': { label: 'Signalized Intersection', group: 'location_access' }, 'traffic.vehiclesPerDay': { label: 'Traffic Count', group: 'location_access' },
  'site.zoning': { label: 'Zoning', group: 'site' }, 'site.utilities': { label: 'Utilities', group: 'site' }, 'site.detentionClaim': { label: 'Detention', group: 'site' }, 'site.floodplainClaim': { label: 'Floodplain', group: 'site' }, 'site.wetlandsClaim': { label: 'Wetlands', group: 'site' }, 'site.easementClaim': { label: 'Easements', group: 'site' }, 'site.pipelineClaim': { label: 'Pipeline', group: 'site' }, 'site.wellClaim': { label: 'Well', group: 'site' }, 'site.cityLimitStatus': { label: 'City Limits', group: 'site' }, 'site.etjStatus': { label: 'ETJ', group: 'site' }, 'site.municipalDistrict': { label: 'Municipal District', group: 'site' }, 'site.tirz': { label: 'TIRZ', group: 'site' },
  'broker.brokerage': { label: 'Brokerage', group: 'broker' }, 'broker.contactName': { label: 'Broker Contact', group: 'broker' }, 'broker.phone': { label: 'Broker Phone', group: 'broker' }, 'broker.email': { label: 'Broker Email', group: 'broker' }, 'marketing.suggestedUse': { label: 'Suggested Use', group: 'marketing' },
};
const GROUPS: Array<{ key: ReviewGroupKey; label: string }> = [{ key: 'property', label: 'Property' }, { key: 'pricing', label: 'Pricing' }, { key: 'location_access', label: 'Location & Access' }, { key: 'site', label: 'Site' }, { key: 'broker', label: 'Broker' }, { key: 'marketing', label: 'Marketing / Use' }, { key: 'other', label: 'Other' }];
export function buildExtractionReviewModel(input: { attemptNumber: number; completedAt: string | null; candidates: ExtractionReviewCandidate[] }): ExtractionReviewModel {
  const represented = new Set(input.candidates.map(c => c.fieldPath)); const counts = new Map<string, number>(); for (const c of input.candidates) counts.set(c.fieldPath, (counts.get(c.fieldPath) ?? 0) + 1);
  const items = input.candidates.map(c => { const definition = LAND_FLYER_SOURCE_DESTINATIONS[c.fieldPath as LandFlyerSourceFieldPath]; const presentation = presentationFor(c.fieldPath); const cardinality = definition?.cardinality ?? 'scalar'; const { id: _id, fingerprint: _fingerprint, ...publicCandidate } = c; void _id; void _fingerprint; return { ...publicCandidate, key: `${c.fieldPath}:${c.ordinal}`, ...presentation, formattedValue: formatCandidateValue(c.valueType, c.value, c.unit), cardinality, scalarConflict: cardinality === 'scalar' && (counts.get(c.fieldPath) ?? 0) > 1, humanReviewStatus: c.decisionCount > 0 ? 'reviewed' as const : 'unreviewed' as const }; });
  const groups = GROUPS.map(group => ({ ...group, items: items.filter(item => item.group === group.key).sort((a, b) => a.ordinal - b.ordinal) })).filter(group => group.items.length > 0);
  const missingDestinations = Object.keys(LAND_FLYER_SOURCE_DESTINATIONS).filter(path => !represented.has(path)).map(fieldPath => ({ fieldPath, ...presentationFor(fieldPath) }));
  return { attemptNumber: input.attemptNumber, completedAt: input.completedAt, factCount: input.candidates.length, representedDestinationCount: represented.size, registryDestinationCount: Object.keys(LAND_FLYER_SOURCE_DESTINATIONS).length, missingDestinationCount: missingDestinations.length, decisionCount: input.candidates.reduce((sum, c) => sum + c.decisionCount, 0), groups, missingDestinations };
}
function presentationFor(fieldPath: string) { return P[fieldPath] ?? { label: (fieldPath.split('.').at(-1) ?? fieldPath).replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/^./, c => c.toUpperCase()), group: 'other' as const }; }
function numeric(value: unknown) { return typeof value === 'string' && /^-?(?:0|[1-9]\d*)(?:\.\d+)?$/.test(value) ? value : null; }
function grouped(value: string) { const negative = value.startsWith('-'); const unsigned = negative ? value.slice(1) : value; const [whole, fraction] = unsigned.split('.'); const result = whole.replace(/\B(?=(\d{3})+(?!\d))/g, ','); return `${negative ? '-' : ''}${result}${fraction === undefined ? '' : `.${fraction}`}`; }
export function formatCandidateValue(type: CandidateValueType, value: unknown, unit: CandidateUnit | null): string {
  if (type === 'boolean') return value === true ? 'Yes' : value === false ? 'No' : 'Not provided'; if (value === null || value === undefined || value === '') return 'Not provided'; if (type === 'json') return JSON.stringify(value); const text = String(value); const number = numeric(text);
  if ((type === 'decimal' || type === 'integer') && number !== null) { const formatted = grouped(number); if (unit === 'USD') return `${number.startsWith('-') ? '-$' : '$'}${grouped(number.replace(/^-/, ''))}`; if (unit === 'USD_PER_LAND_SF') { const [whole, fraction = ''] = grouped(number).split('.'); return `${whole.startsWith('-') ? '-$' + whole.slice(1) : '$' + whole}.${fraction.padEnd(2, '0')} / SF`; } const suffix: Partial<Record<CandidateUnit, string>> = { ACRES: ' acres', SF: ' SF', FEET: ' ft', VEHICLES_PER_DAY: ' vehicles/day', MONTHS: ' months', DAYS: ' days', COUNT: '' }; return `${formatted}${suffix[unit ?? 'NONE'] ?? ''}`; } return text;
}
