import { describe, expect, it, vi } from 'vitest';
vi.mock('server-only', () => ({}));
import type { SupabaseClient } from '@supabase/supabase-js';
import { currentExtractionLogicalKey } from './extraction-control';
import { SupabaseExtractionReviewRepository } from './supabase-extraction-review-repository';

const digest = 'a'.repeat(64); const currentKey = currentExtractionLogicalKey(digest);
const oldRun = { id:'v1',attempt_number:1,completed_at:'2026-08-28T00:00:00Z',created_at:'2026-08-28T00:00:00Z',logical_extraction_key:'extract:legacy',extraction_version:'openai-land-flyer-v1',schema_version:'land-flyer-v1' };
const currentRun = { id:'v3',attempt_number:1,completed_at:'2026-08-31T00:00:00Z',created_at:'2026-08-31T00:00:00Z',logical_extraction_key:currentKey,extraction_version:'openai-land-flyer-v3',schema_version:'land-flyer-v3' };
function candidate(id:string,value:string){return{id,field_path:'land.areaSf',normalized_value_type:'decimal',normalized_value:value,unit:'SF',group_key:null,assertion_basis:'source_stated',confidence:null,validation_state:'valid',validation_issues:[],ordinal:0,candidate_fingerprint:'b'.repeat(64)}}
function fakeClient(results: Array<{ data: unknown; error: unknown }>) { const calls: Array<{ table: string; eq: Array<[string, unknown]> }> = [];
  const from = vi.fn((table: string) => { const result = results.shift() ?? { data: null, error: null }; const call = { table, eq: [] as Array<[string, unknown]> }; calls.push(call); const chain: Record<string, unknown> = {};
    for (const method of ['select','order','limit','in']) chain[method] = vi.fn(() => chain); chain.eq = vi.fn((key: string, value: unknown) => { call.eq.push([key, value]); return chain; }); chain.maybeSingle = vi.fn(async () => result); chain.then = (resolve: (value: unknown) => unknown) => Promise.resolve(result).then(resolve); return chain; });
  return { client: { from } as unknown as SupabaseClient, calls }; }
function prefix(runs:unknown[]){return[{data:{id:'opp'},error:null},{data:[{id:'ing'}],error:null},{data:{id:'art',ingestion_id:'ing',sha256_digest:digest},error:null},{data:runs,error:null}]}
function emptyChildren(){return[{data:[],error:null}]}
function candidateChildren(id:string,value:string,decision:'accepted'|'rejected'|null=null){return[{data:[candidate(id,value)],error:null},{data:[],error:null},{data:decision?[{candidate_fact_id:id,decision_number:1,decision,decided_at:'2026-08-30T01:00:00Z'}]:[],error:null}]}
function katyReviewedChildren(){const candidates=Array.from({length:14},(_,index)=>({...candidate(`katy-${index}`,String(1000+index)),ordinal:index}));const decisions=candidates.map(row=>({candidate_fact_id:row.id,decision_number:1,decision:'accepted',decided_at:'2026-08-30T01:00:00Z'}));return[{data:candidates,error:null},{data:[],error:null},{data:decisions,error:null}]}

describe('Supabase extraction review lineage selection',()=>{
  it('reproduces Katy: 14 reviewed V1 facts remain historical while current V2 is absent',async()=>{const fake=fakeClient([...prefix([oldRun]),...katyReviewedChildren()]);const result=await new SupabaseExtractionReviewRepository(fake.client).getReviewSelection('opp');expect(result.current).toBeNull();expect(result.historical).toHaveLength(1);expect(result.historical[0]).toMatchObject({schemaVersion:'land-flyer-v1',factCount:14,approvedCount:14,unreviewedCount:0});});
  it('selects V3 as current and retains V1 decisions only in its historical model',async()=>{const fake=fakeClient([...prefix([currentRun,oldRun]),...candidateChildren('new','2000'),...candidateChildren('old','1000','accepted')]);const result=await new SupabaseExtractionReviewRepository(fake.client).getReviewSelection('opp');expect(result.current).toMatchObject({schemaVersion:'land-flyer-v3',factCount:1,unreviewedCount:1,approvedCount:0});expect(result.historical[0]).toMatchObject({schemaVersion:'land-flyer-v1',approvedCount:1});expect(result.current?.groups[0].items[0].candidateId).toBe('new');});
  it('returns a current-only V3 review without manufacturing history',async()=>{const fake=fakeClient([...prefix([currentRun]),...emptyChildren()]);await expect(new SupabaseExtractionReviewRepository(fake.client).getReviewSelection('opp')).resolves.toMatchObject({current:{schemaVersion:'land-flyer-v3',factCount:0},historical:[]});});
  it('chooses the highest attempt inside the current logical lineage, independent of historical attempts',async()=>{const retry={...currentRun,id:'v2-retry',attempt_number:2,completed_at:'2026-08-30T02:00:00Z'};const fake=fakeClient([...prefix([retry,currentRun,oldRun]),...candidateChildren('retry','3000'),...candidateChildren('old','1000')]);const result=await new SupabaseExtractionReviewRepository(fake.client).getReviewSelection('opp');expect(result.current).toMatchObject({attemptNumber:2});expect(result.historical).toHaveLength(1);});
  it('returns empty current and history when no successful run exists',async()=>{const fake=fakeClient([...prefix([])]);await expect(new SupabaseExtractionReviewRepository(fake.client).getReviewSelection('opp')).resolves.toEqual({current:null,historical:[]});expect(fake.calls.some(call=>call.table==='opportunity_candidate_facts')).toBe(false);});
});
