import 'server-only';
import type { SupabaseClient } from '@supabase/supabase-js';
import { opportunityError } from '@/lib/opportunities/application/errors';
import type { PropertyIdentityModel, PropertyMatch, ResolvePropertyIdentityInput, ResolvePropertyIdentityResult, ReviewedAlias, SubjectProposalType } from './contracts';
type CurrentRow={authority_state:string;proposal_id:string|null;entity_id:string|null;opportunity_subject_id:string|null;display_name:string|null;proposal_type:SubjectProposalType|null;decision_number:number|null;decided_at:string|null};
const one=<T>(data:unknown,error:unknown):T=>{if(error||!Array.isArray(data)||data.length!==1)throw opportunityError('persistence_failure','Property identity authority could not be loaded.',error);return data[0] as T};
function scalarText(value:unknown){return typeof value==='string'?value:null}
function escapeLike(value:string){return value.replace(/[\\%_]/g,c=>`\\${c}`)}
export class SupabaseSubjectResolutionRepository{
  constructor(private readonly client:SupabaseClient){}
  async getModel(opportunityId:string):Promise<Omit<PropertyIdentityModel,'commandId'>>{
    const [{data:opportunity,error:opportunityFailure},{data:authority,error:authorityFailure}]=await Promise.all([
      this.client.from('acquisition_opportunities').select('id,name').eq('id',opportunityId).single(),
      this.client.rpc('get_intelligence_opportunity_primary_target_v1',{p_opportunity_id:opportunityId}),
    ]);
    if(opportunityFailure||!opportunity)throw opportunityError(opportunityFailure?.code==='PGRST116'?'not_found':'persistence_failure','Opportunity Property identity could not be loaded.',opportunityFailure);
    const current=one<CurrentRow>(authority,authorityFailure);
    const supportingContext=await this.supportingContext(opportunityId);
    const displayLabel=supportingContext[0]??opportunity.name;
    const proposedAliases:ReviewedAlias[]=displayLabel!==opportunity.name?[{aliasType:'property_name',aliasValue:opportunity.name}]:[];
    const possibleMatches=await this.possibleMatches([displayLabel,opportunity.name,...supportingContext]);
    return {opportunityId,opportunityName:opportunity.name,authorityState:current.authority_state as PropertyIdentityModel['authorityState'],current:current.authority_state==='confirmed'?{proposalId:current.proposal_id!,entityId:current.entity_id!,opportunitySubjectId:current.opportunity_subject_id!,displayName:current.display_name!,proposalType:current.proposal_type!,decisionNumber:current.decision_number!,decidedAt:current.decided_at!}:null,suggestion:{displayLabel,aliases:proposedAliases,supportingContext},possibleMatches};
  }
  async resolve(opportunityId:string,input:ResolvePropertyIdentityInput,reviewerEmail:string):Promise<ResolvePropertyIdentityResult>{
    const {data,error}=await this.client.rpc('resolve_intelligence_opportunity_primary_target_v1',{p_command_id:input.commandId,p_opportunity_id:opportunityId,p_action:input.action,p_proposal_type:input.proposalType,p_existing_entity_id:input.existingEntityId,p_display_label:input.displayLabel,p_aliases:input.aliases,p_corrects_proposal_id:input.correctsProposalId,p_reviewer_email:reviewerEmail});
    if(error)throw translate(error);const row=one<Record<string,unknown>>(data,null);return {proposalId:row.proposal_id as string,decisionNumber:row.decision_number as number,decision:row.decision as ResolvePropertyIdentityResult['decision'],subjectEntityId:row.subject_entity_id as string|null,opportunitySubjectId:row.opportunity_subject_id as string|null,inserted:row.inserted as boolean};
  }
  private async supportingContext(opportunityId:string){const {data:ingestions,error}=await this.client.from('opportunity_ingestions').select('id').eq('opportunity_id',opportunityId);if(error)throw opportunityError('persistence_failure','Property identity context could not be loaded.',error);const ids=(ingestions??[]).map(x=>x.id);if(ids.length===0)return[];const {data:candidates,error:candidateError}=await this.client.from('opportunity_candidate_facts').select('id').in('ingestion_id',ids).eq('field_path','location.intersection');if(candidateError)throw opportunityError('persistence_failure','Property identity context could not be loaded.',candidateError);const candidateIds=(candidates??[]).map(x=>x.id);if(candidateIds.length===0)return[];const {data:decisions,error:decisionError}=await this.client.from('opportunity_candidate_fact_decisions').select('candidate_fact_id,decision_number,decision,accepted_value').in('candidate_fact_id',candidateIds).order('decision_number',{ascending:false});if(decisionError)throw opportunityError('persistence_failure','Property identity context could not be loaded.',decisionError);const latest=new Map<string,Record<string,unknown>>();for(const d of decisions??[])if(!latest.has(d.candidate_fact_id))latest.set(d.candidate_fact_id,d);return [...latest.values()].filter(d=>d.decision==='accepted').map(d=>scalarText(d.accepted_value)).filter((x):x is string=>x!==null).slice(0,3)}
  private async possibleMatches(labels:string[]):Promise<PropertyMatch[]>{const unique=[...new Set(labels.map(x=>x.trim()).filter(Boolean))];const results=new Map<string,PropertyMatch>();for(const label of unique){const pattern=escapeLike(label);const [{data:entities,error:entityError},{data:aliases,error:aliasError}]=await Promise.all([this.client.from('intelligence_entities').select('id,display_name,intelligence_property_sites!inner(entity_id)').ilike('display_name',pattern),this.client.from('intelligence_entity_aliases').select('entity_id,alias_value,intelligence_entities!inner(id,display_name,entity_type)').ilike('alias_value',pattern).eq('intelligence_entities.entity_type','property_site')]);if(entityError||aliasError)throw opportunityError('persistence_failure','Possible Property matches could not be loaded.',entityError??aliasError);for(const entity of entities??[])results.set(entity.id,{entityId:entity.id,displayName:entity.display_name,matchedBy:'display_name'});for(const alias of aliases??[]){const entity=alias.intelligence_entities as unknown as {id:string;display_name:string};if(entity&&!results.has(entity.id))results.set(entity.id,{entityId:entity.id,displayName:entity.display_name,matchedBy:'alias'})}}return [...results.values()].sort((a,b)=>a.displayName.localeCompare(b.displayName)).slice(0,20)}
}
function translate(cause:unknown){const e=cause as {code?:string;message?:string};if(e.message==='intelligence_opportunity_subject_command_semantics_conflict')return opportunityError('idempotency_conflict','The command identifier was already used with different semantics.',cause);if(e.message?.includes('current_authority_conflict')||e.code==='23505')return opportunityError('revision_conflict','Property identity authority changed. Refresh before retrying.',cause);if(e.code==='P0002')return opportunityError('not_found','The Opportunity or Property identity was not found.',cause);if(e.code?.startsWith('22')||e.code?.startsWith('23'))return opportunityError('integrity_conflict','The Property identity judgment conflicts with durable authority.',cause);return opportunityError('persistence_failure','The Property identity judgment could not be completed.',cause)}
