import { opportunityError } from '../../opportunities/application/errors';
import type { ResolvePropertyIdentityInput, ReviewedAlias } from './contracts';
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const CONTROL=/[\u0000-\u001f\u007f-\u009f]/u;
function exact(value:Record<string,unknown>,keys:string[]){if(Object.keys(value).some(k=>!keys.includes(k))||keys.some(k=>!(k in value)))throw opportunityError('validation','Request contains invalid properties.')}
function uuid(value:unknown,name:string,nullable=false){if(nullable&&value===null)return null;if(typeof value!=='string'||!UUID.test(value))throw opportunityError('validation',`${name} is invalid.`);return value}
function text(value:unknown,name:string,nullable=false){if(nullable&&value===null)return null;if(typeof value!=='string'||value!==value.trim()||value.length<1||[...value].length>200||CONTROL.test(value))throw opportunityError('validation',`${name} is invalid.`);return value}
function aliases(value:unknown):ReviewedAlias[]{if(!Array.isArray(value)||value.length>5)throw opportunityError('validation','aliases is invalid.');const seen=new Set<string>();return value.map((item,index)=>{if(!item||typeof item!=='object'||Array.isArray(item))throw opportunityError('validation',`aliases[${index}] is invalid.`);const row=item as Record<string,unknown>;exact(row,['aliasType','aliasValue']);if(row.aliasType!=='property_name'&&row.aliasType!=='other')throw opportunityError('validation',`aliases[${index}].aliasType is invalid.`);const aliasValue=text(row.aliasValue,`aliases[${index}].aliasValue`) as string;const key=`${row.aliasType}\0${aliasValue}`;if(seen.has(key))throw opportunityError('validation','aliases contains a duplicate.');seen.add(key);return {aliasType:row.aliasType,aliasValue}})}
export function parseResolutionRequest(value:unknown):ResolvePropertyIdentityInput{if(!value||typeof value!=='object'||Array.isArray(value))throw opportunityError('validation','Request must be an object.');const row=value as Record<string,unknown>;exact(row,['action','commandId','proposalType','existingEntityId','displayLabel','aliases','correctsProposalId']);if(row.action!=='confirm'&&row.action!=='reject'&&row.action!=='ambiguous')throw opportunityError('validation','action is invalid.');if(row.proposalType!=='new_property'&&row.proposalType!=='existing_property')throw opportunityError('validation','proposalType is invalid.');const result:ResolvePropertyIdentityInput={action:row.action,commandId:uuid(row.commandId,'commandId')!,proposalType:row.proposalType,existingEntityId:uuid(row.existingEntityId,'existingEntityId',true),displayLabel:text(row.displayLabel,'displayLabel',true),aliases:aliases(row.aliases),correctsProposalId:uuid(row.correctsProposalId,'correctsProposalId',true)};if(result.proposalType==='new_property'&&(result.existingEntityId!==null||result.displayLabel===null))throw opportunityError('validation','New Property proposals require only reviewed display identity.');if(result.proposalType==='existing_property'&&(result.existingEntityId===null||result.displayLabel!==null||result.aliases.length!==0))throw opportunityError('validation','Existing Property proposals must select one authorized match.');return result}
