import { createHash } from 'node:crypto';
import type { CreateProposalCommand, DecideProposalCommand, ProposalPayload, UpstreamPayload } from './contracts';
const hex=(value:string)=>Buffer.from(value.normalize('NFC'),'utf8').toString('hex');
const nullable=(value:string|null)=>value===null?'null':value;
const canonicalJson=(value:unknown):string=>{if(value===null||typeof value==='boolean'||typeof value==='number')return JSON.stringify(value);if(typeof value==='string')return JSON.stringify(value.normalize('NFC'));if(Array.isArray(value))return `[${value.map(canonicalJson).join(',')}]`;const record=value as Record<string,unknown>;return `{${Object.keys(record).sort().map(key=>`${JSON.stringify(key)}:${canonicalJson(record[key])}`).join(',')}}`};
export const sha256=(value:string)=>createHash('sha256').update(value,'utf8').digest('hex');
export function canonicalProposalPayload(kind:CreateProposalCommand['proposalKind'],payload:ProposalPayload):string{if(kind==='source_identity'){const p=payload as Extract<ProposalPayload,{candidateTitle:string}>;return ['source_identity',p.resolutionMode,nullable(p.existingSourceId),nullable(p.publisherId),hex(p.candidateTitle),p.candidateSourceKind,p.candidateExternalIdentifier===null?'null':hex(p.candidateExternalIdentifier),p.publisherEvidence,p.matchTitle,p.matchFilename,p.matchProperty,p.matchPublisher,p.matchUploader].join('|')}if(kind==='source_edition'){const p=payload as Extract<ProposalPayload,{publicationPrecision:string}>;return ['source_edition',p.sourceId,p.resolutionMode,nullable(p.existingEditionId),p.editionLabel===null?'null':hex(p.editionLabel),p.publicationPrecision,p.publicationYear??'null',p.publicationMonth??'null',p.publicationDay??'null',p.publicationAuthority].join('|')}if(kind==='artifact_representation'){const p=payload as Extract<ProposalPayload,{representationRole:string}>;return ['artifact_representation',p.sourceEditionId,p.artifactId,p.representationRole,p.isPrimary,p.contentEquivalenceState,p.contentEquivalenceAuthority].join('|')}const p=payload as Extract<ProposalPayload,{conclusion:string}>;return ['upstream_attribution',p.containingSourceEditionId,p.conclusion,nullable(p.relationshipType),nullable(p.upstreamSourceId),nullable(p.upstreamSourceEditionId),nullable(p.upstreamEditionState),nullable(p.independenceAuthority),p.humanReviewRationale===null?'null':hex(p.humanReviewRationale),p.evidenceLocationIds.length?[...p.evidenceLocationIds].sort().join(','):'null'].join('|')}
export function canonicalCreateRequest(command:CreateProposalCommand,actorEmail:string):string{const payload=command.proposalKind==='upstream_attribution'?{...command.payload,evidenceLocationIds:[...(command.payload as UpstreamPayload).evidenceLocationIds].sort()}:command.payload;return canonicalJson({...command,payload,proposedByEmail:actorEmail.normalize('NFC')})}
export function canonicalDecisionRequest(command:DecideProposalCommand,actorEmail:string):string{return canonicalJson({...command,reviewerEmail:actorEmail.normalize('NFC')})}
