import {describe,expect,it} from 'vitest';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {parseHumanStage} from './control-validation';
const read=(p:string)=>readFileSync(join(process.cwd(),p),'utf8');
describe('Phase 4C.3.3A human provenance control boundary',()=>{
  it('protects both read and mutation routes with established authentication',()=>{expect(read('src/app/api/intelligence/provenance-control/route.ts')).toContain('authenticatedOpportunityEndpoint');expect(read('src/app/api/intelligence/provenance-resolution/route.ts')).toContain('authenticatedOpportunityEndpoint')});
  it('keeps reviewer and database authority out of the browser contract',()=>{const client=read('src/components/intelligence/ProvenanceControl.tsx');expect(client).not.toMatch(/reviewerEmail|reviewerRole|humanConfirmed|proposalOrigin|semanticFingerprint|commandDigest|materializedSource|materializedEdition|materializedRepresentation|currentAuthority/);expect(client).toContain("operation:'confirm_stage'")});
  it('routes every human mutation through the existing B.2 service and RPC repository',()=>{const control=read('src/lib/intelligence/provenance-resolution/control.ts');expect(control).toContain('executeProvenanceCommand');expect(control).toContain('SupabaseProvenanceResolutionRepository');expect(control).not.toMatch(/\.from\([^)]*provenance[^)]*\)\.(?:insert|update|delete|upsert)/)});
  it('derives readiness and private object identity server-side',()=>{const control=read('src/lib/intelligence/provenance-resolution/control.ts');expect(control).toContain('repository.getReadiness');expect(control).toContain('createExactReadAccess');expect(control).toContain("select('id,artifact_id,opportunity_id,legacy_opportunity_artifact_id")});
  it('uses stable per-stage command IDs so refresh and retry replay safely',()=>{const client=read('src/components/intelligence/ProvenanceControl.tsx');expect(client).toContain('localStorage.getItem(key)');expect(client).toContain('createCommandId:crypto.randomUUID()');expect(client).toContain('decisionCommandId:crypto.randomUUID()')});
  it('accepts the exact Mason source judgment without serializing the local storage key',()=>{const body={operation:'confirm_stage',opportunityId:'3a24a91f-a0c0-4cfc-96a2-8d4f00282e63',artifactAcquisitionId:'49626250-4e6e-47fd-a7cf-e5de1e8112e2',createCommandId:'30000000-0000-4000-8000-000000000001',decisionCommandId:'40000000-0000-4000-8000-000000000001',judgment:{stage:'source_unresolved',title:'NW Corner of Mason Rd. @ Mason Manor Dr.',sourceKind:'marketing_material',matchTitle:true,matchProperty:true}};expect(parseHumanStage(body)).toEqual(body);const client=read('src/components/intelligence/ProvenanceControl.tsx');expect(client).toContain('const{key,...ids}=commandIds');expect(client).toContain('localStorage.removeItem(key)');expect(client).not.toContain('localStorage.removeItem(ids.key)')});
  it('continues to reject the leaked local storage key and other browser authority',()=>{const body={operation:'confirm_stage',opportunityId:'3a24a91f-a0c0-4cfc-96a2-8d4f00282e63',artifactAcquisitionId:'49626250-4e6e-47fd-a7cf-e5de1e8112e2',createCommandId:'30000000-0000-4000-8000-000000000001',decisionCommandId:'40000000-0000-4000-8000-000000000001',key:'upperline:provenance:internal',judgment:{stage:'source_unresolved',title:'NW Corner of Mason Rd. @ Mason Manor Dr.',sourceKind:'marketing_material',matchTitle:true,matchProperty:true}};expect(()=>parseHumanStage(body)).toThrow('Request contains invalid properties.')});
  it('keeps the PDF and repository implementation server-only',()=>{const control=read('src/lib/intelligence/provenance-resolution/control.ts');expect(control).toContain("import 'server-only'");expect(control).not.toContain('globalArtifactId:');expect(read('src/components/intelligence/ProvenanceControl.tsx')).not.toMatch(/SUPABASE_SERVICE_ROLE_KEY|storage_bucket|storage_path|sha256|signedUrl|globalArtifactId/)})
  it('binds every mutation to both Opportunity and acquisition identity',()=>{const control=read('src/lib/intelligence/provenance-resolution/control.ts');expect(control).toContain('loadBoundAcquisition(client,request.opportunityId,request.artifactAcquisitionId)');expect(control).toContain(".eq('opportunity_id',opportunityId)");expect(control).toContain(".eq('id',artifactAcquisitionId)");expect(control).toContain('ingestion.opportunity_id!==opportunityId')});
  it('does not retain the low-level browser command bypass',()=>{const route=read('src/app/api/intelligence/provenance-resolution/route.ts');expect(route).not.toContain('executeProvenanceCommand');expect(route).toContain('executeHumanProvenanceStage')});
  it.each(['reviewerEmail','proposalOrigin','artifactId','sourceId','editionId','representationId','semanticFingerprint','canonicalRequest','timestamp','readiness','materializedSourceId','expectedDecisionNumber'])('rejects injected authority field %s',field=>{const body={operation:'confirm_stage',opportunityId:'10000000-0000-4000-8000-000000000001',artifactAcquisitionId:'20000000-0000-4000-8000-000000000001',createCommandId:'30000000-0000-4000-8000-000000000001',decisionCommandId:'40000000-0000-4000-8000-000000000001',judgment:{stage:'source_unresolved'},[field]:'forged'};expect(()=>parseHumanStage(body)).toThrow()});
  it('requires the Opportunity identity in the mutation contract',()=>{const body={operation:'confirm_stage',artifactAcquisitionId:'20000000-0000-4000-8000-000000000001',createCommandId:'30000000-0000-4000-8000-000000000001',decisionCommandId:'40000000-0000-4000-8000-000000000001',judgment:{stage:'source_unresolved'}};expect(()=>parseHumanStage(body)).toThrow()});
  it('constrains no-upstream rationale and explains its narrow meaning',()=>{const client=read('src/components/intelligence/ProvenanceControl.tsx');const control=read('src/lib/intelligence/provenance-resolution/control.ts');expect(client).toContain('maxLength={2000}');expect(client).toContain('does not assert source independence or absence of citations');expect(control).toContain("[...value].length>2000");expect(control).toMatch(/\\u0000-\\u001f\\u007f-\\u009f/)});
  it('requires an explicit no-upstream affirmation and dedicated action',()=>{const client=read('src/components/intelligence/ProvenanceControl.tsx');const control=read('src/lib/intelligence/provenance-resolution/control.ts');expect(client).toContain('name="affirmNoUpstream" type="checkbox" required');expect(client).toContain('Affirm no upstream attribution required');expect(control).toContain("request.judgment.affirmNoUpstream!==true")});
});
