export const PROVENANCE_PROPOSAL_KINDS = ['source_identity','source_edition','artifact_representation','upstream_attribution'] as const;
export type ProvenanceProposalKind = typeof PROVENANCE_PROPOSAL_KINDS[number];
export type ProposalOrigin = 'human_review' | 'deterministic_system' | 'machine_assisted';
export type DecisionIntent = 'confirm' | 'reject' | 'mark_ambiguous' | 'reverse';
export type SourcePayload = { resolutionMode:'select_existing'|'create_new'; existingSourceId:string|null; publisherId:string|null; candidateTitle:string; candidateSourceKind:string; candidateExternalIdentifier:string|null; publisherEvidence:'none'|'matching_evidence'|'preauthorized_identity'; matchTitle:boolean; matchFilename:boolean; matchProperty:boolean; matchPublisher:boolean; matchUploader:boolean };
export type EditionPayload = { sourceId:string; resolutionMode:'select_existing'|'create_new'; existingEditionId:string|null; editionLabel:string|null; publicationPrecision:'unknown'|'year'|'month'|'day'; publicationYear:number|null; publicationMonth:number|null; publicationDay:number|null; publicationAuthority:'unknown'|'source_explicit'|'human_confirmed' };
export type RepresentationPayload = { sourceEditionId:string; artifactId:string; representationRole:'primary'|'supplement'|'embedded'|'derivative'; isPrimary:boolean; contentEquivalenceState:'same_bytes'|'reviewed_equivalent'|'unreviewed_different_bytes'; contentEquivalenceAuthority:'database_derived'|'human_decision' };
export type UpstreamPayload = { containingSourceEditionId:string; conclusion:'attributed_upstream'|'no_upstream_required'; relationshipType:string|null; upstreamSourceId:string|null; upstreamSourceEditionId:string|null; upstreamEditionState:'preauthorized'|'unidentified'|null; independenceAuthority:'not_established'|null; humanReviewRationale:string|null; evidenceLocationIds:string[] };
export type ProposalPayload = SourcePayload|EditionPayload|RepresentationPayload|UpstreamPayload;
export type CreateProposalCommand = { operation:'create_proposal'; commandId:string; artifactAcquisitionId:string; proposalKind:ProvenanceProposalKind; proposalOrigin:ProposalOrigin; correctsProposalId:string|null; payload:ProposalPayload };
export type DecideProposalCommand = { operation:'decide_proposal'; commandId:string; proposalId:string; action:DecisionIntent; expectedDecisionNumber:number; rationale:string|null };
export type ReadinessQuery = { artifactAcquisitionId:string };
export type ProposalResult = { proposalId:string; inserted:boolean; readiness:string };
export type DecisionResult = { proposalId:string; decisionNumber:number; currentState:string; inserted:boolean; readiness:string; materializedSourceId:string|null; materializedEditionId:string|null; materializedRepresentationId:string|null; materializedSourceRelationshipId:string|null };
export type ReadinessResult = { readiness:string; sourceId:string|null; editionId:string|null; representationId:string|null; sourceRelationshipId:string|null };
export interface ProvenanceResolutionRepository { createProposal(input: CreateProposalCommand & { proposedByEmail:string; semanticFingerprint:string; canonicalRequest:string }):Promise<ProposalResult>; decideProposal(input: DecideProposalCommand & { reviewerEmail:string; canonicalRequest:string }):Promise<DecisionResult>; getReadiness(input:ReadinessQuery):Promise<ReadinessResult> }
