import { describe,expect,it,vi } from 'vitest';
import { executeProvenanceCommand } from './service';
import type { ProvenanceResolutionRepository } from './contracts';
const U={command:'10000000-0000-4000-8000-000000000001',acquisition:'20000000-0000-4000-8000-000000000001',source:'30000000-0000-4000-8000-000000000001'};
const actor={email:'reviewer@upperlineco.com',name:'Reviewer'};
const repo=()=>({createProposal:vi.fn(async()=>({proposalId:U.source,inserted:true,readiness:'source_unresolved'})),decideProposal:vi.fn(async()=>({proposalId:U.source,decisionNumber:1,currentState:'confirmed',inserted:true,readiness:'edition_unresolved',materializedSourceId:U.source,materializedEditionId:null,materializedRepresentationId:null,materializedSourceRelationshipId:null})),getReadiness:vi.fn()} satisfies ProvenanceResolutionRepository);
const sourceBody={operation:'create_proposal',commandId:U.command,artifactAcquisitionId:U.acquisition,proposalKind:'source_identity',correctsProposalId:null,payload:{resolutionMode:'select_existing',existingSourceId:U.source,publisherId:null,candidateTitle:'Mason Flyer',candidateSourceKind:'offering_memorandum',candidateExternalIdentifier:null,publisherEvidence:'matching_evidence',matchTitle:true,matchFilename:true,matchProperty:true,matchPublisher:false,matchUploader:false}};
describe('provenance orchestration service',()=>{
  it('derives actor identity, human origin, fingerprint, and digest semantics server-side',async()=>{const repository=repo();await executeProvenanceCommand(sourceBody,actor,repository);expect(repository.createProposal).toHaveBeenCalledWith(expect.objectContaining({proposalOrigin:'human_review',proposedByEmail:actor.email,semanticFingerprint:expect.stringMatching(/^[0-9a-f]{64}$/),canonicalRequest:expect.stringContaining(actor.email)}));});
  it.each(['reviewerEmail','humanConfirmed','proposalOrigin','semanticFingerprint','requestDigest','readiness','materializedSourceId'])('rejects caller authority field %s',async field=>{const repository=repo();await expect(executeProvenanceCommand({...sourceBody,[field]:'forged'},actor,repository)).rejects.toMatchObject({kind:'validation'});expect(repository.createProposal).not.toHaveBeenCalled()});
  it.each(['publicationAuthority','contentEquivalenceAuthority'])('rejects nested caller authority field %s',async field=>{const repository=repo();await expect(executeProvenanceCommand({...sourceBody,payload:{...sourceBody.payload,[field]:'human_confirmed'}},actor,repository)).rejects.toMatchObject({kind:'validation'});expect(repository.createProposal).not.toHaveBeenCalled()});
  it('persists a decision with only the server-derived reviewer',async()=>{const repository=repo();await executeProvenanceCommand({operation:'decide_proposal',commandId:U.command,proposalId:U.source,action:'confirm',expectedDecisionNumber:0,rationale:null},actor,repository);expect(repository.decideProposal).toHaveBeenCalledWith(expect.objectContaining({reviewerEmail:actor.email,canonicalRequest:expect.stringContaining(actor.email)}))});
  it('rejects caller-supplied reviewer identity on decisions',async()=>{await expect(executeProvenanceCommand({operation:'decide_proposal',commandId:U.command,proposalId:U.source,action:'confirm',expectedDecisionNumber:0,rationale:null,reviewerEmail:'attacker@example.com'},actor,repo())).rejects.toMatchObject({kind:'validation'})});
});
