import { describe, expect, it } from 'vitest';
import Decimal from 'decimal.js';
import { calculateRetailDevelopmentUnderwriting, edate, totalBaseRent, validateInput } from '..';
import { canonicalInput, canonicalTenants, marketInput } from './fixtures/canonical';
const n = (value: string | null | undefined) => value == null ? NaN : Number(value);
const clone = <T>(value: T): T => structuredClone(value);

describe('date and rent policies', () => {
  it.each([['2026-01-15',1,'2026-02-15'],['2026-01-31',1,'2026-02-28'],['2024-01-31',1,'2024-02-29'],['2024-02-29',12,'2025-02-28'],['2026-03-31',-1,'2026-02-28']] as const)('applies EDATE to %s', (date, months, expected) => expect(edate(date, months)).toBe(expected));
  it('uses straight term rent for zero bumps', () => expect(totalBaseRent(new Decimal(100), new Decimal(0), 60).toString()).toBe('500'));
  it('compounds positive bumps', () => expect(totalBaseRent(new Decimal(100), new Decimal('0.03'), 120).toDecimalPlaces(6).toString()).toBe('1146.387931'));
});

describe('market assumptions full model', () => {
  const result = calculateRetailDevelopmentUnderwriting(marketInput);
  it('is complete in market mode', () => { expect(result.complete).toBe(true); expect(result.resolvedLeasing?.source).toBe('market'); });
  it('calculates acres and GLA', () => { expect(result.geometry).toEqual({ landAreaAcres: '2', buildingAreaSf: '21780' }); });
  it('calculates the cost lines', () => { const c=result.developmentCosts!; expect(c.landCost).toBe('1568160'); expect(c.hardCost).toBe('4029300'); expect(c.softCost).toBe('725274'); expect(c.contingency).toBe('356593.05'); expect(c.tenantImprovements).toBe('762300'); expect(c.freeRentCost).toBe('203280'); expect(n(c.leasingCommissions)).toBeCloseTo(349557,0); });
  it('reconciles costs and developer fee', () => { const c=result.developmentCosts!; const subtotal=['landCost','hardCost','softCost','contingency','tenantImprovements','leasingCommissions','freeRentCost'].reduce((a,k)=>a+n(c[k]),0); expect(n(c.subtotalBeforeDeveloperFee)).toBeCloseTo(subtotal,7); expect(n(c.developerFee)).toBeCloseTo(subtotal*.05,7); expect(n(c.developmentCostBeforeFinancing)).toBeCloseTo(subtotal*1.05,7); });
  it('calculates the timeline', () => expect(result.timeline).toEqual({ closingDate:'2026-04-01', designPermittingStart:'2026-04-01', constructionStart:'2026-10-01', constructionCompletion:'2027-10-01', projectedStabilizationSaleDate:'2028-10-01' }));
  it('reconciles financing interest', () => { const f=result.financing!; expect(n(f.totalInterimInterest)).toBeCloseTo(n(f.designPeriodInterest)+n(f.constructionPeriodInterest)+n(f.postCompletionInterest),8); });
  it('calculates lease-up cash flow', () => { const l=result.leaseUpEconomics!; expect(n(l.netLeaseUpOperatingCashFlow)).toBeCloseTo(n(l.rentalIncomeCollected)-n(l.opexCarryOnVacantSpace),8); expect(n(l.unfundedOperatingDeficit)).toBeGreaterThanOrEqual(0); });
  it('applies opex to EGI including other income', () => { const o=result.stabilizedOperations!; expect(n(o.effectiveGrossIncome)).toBeCloseTo(n(o.effectiveRentalIncome)+10000,8); expect(n(o.operatingExpenses)).toBeCloseTo(n(o.effectiveGrossIncome)*.03,8); expect(n(o.netOperatingIncome)).toBeCloseTo(n(o.effectiveGrossIncome)-n(o.operatingExpenses),8); });
  it('calculates disposition and unlevered returns', () => { const d=result.disposition!,u=result.unleveredReturns!; expect(n(d.grossSaleValue)).toBeCloseTo(n(result.stabilizedOperations?.netOperatingIncome)/.0625,7); expect(n(d.netSaleProceeds)).toBeCloseTo(n(d.grossSaleValue)*.98,7); expect(n(u.unleveredProfit)).toBeCloseTo(n(d.netSaleProceeds)-n(result.developmentCosts?.developmentCostBeforeFinancing),7); });
  it('uses corrected equity economics', () => { const e=result.equityReturns!,s=result.sourcesAndUses!; expect(n(e.netCashToEquityAtSale)).toBeCloseTo(n(result.disposition?.netSaleProceeds)-n(result.financing?.constructionLoanPrincipal),7); expect(n(e.equityProfit)).toBeCloseTo(n(e.netCashToEquityAtSale)-n(s.netEquityInvested),7); expect(n(e.equityMultiple)).toBeCloseTo(n(e.netCashToEquityAtSale)/n(s.netEquityInvested),10); expect(e.annualizedEquityReturn).not.toBeNull(); });
  it('reconciles gross and net funding to uses', () => { const s=result.sourcesAndUses!; expect(n(s.debtFunding)+n(s.grossEquityFundingRequirement)).toBeCloseTo(n(s.grossProjectUses),8); expect(n(s.debtFunding)+n(s.netEquityInvested)+n(s.leaseUpOperatingSurplus)).toBeCloseTo(n(s.grossProjectUses),8); expect(s.sourcesAndUsesDifference).toBe('0'); });
  it('does not leak non-finite values', () => expect(JSON.stringify(result)).not.toMatch(/NaN|Infinity/));
});

describe('tenant roster mode', () => {
  const result=calculateRetailDevelopmentUnderwriting(canonicalInput);
  it('resolves exact GLA roster', () => { expect(result.complete).toBe(true); expect(result.resolvedLeasing?.source).toBe('tenantRoster'); expect(result.resolvedLeasing?.totalRosterSf).toBe('21780'); expect(result.diagnostics.some(d=>d.code==='TENANT_SF_BELOW_GLA'||d.code==='TENANT_SF_ABOVE_GLA')).toBe(false); });
  it('calculates ordered tenant rows and expiration', () => { expect(result.tenants).toHaveLength(8); expect(result.tenants.at(-1)?.cumulativeSf).toBe('21780'); expect(result.tenants[0].annualBaseRent).toBe('96000'); expect(result.tenants[0].leaseExpirationDate).toBe('2037-11-01'); });
  it('calculates weighted rent', () => { const expected=canonicalTenants.reduce((a,t)=>a+Number(t.sizeSf)*Number(t.rentalRatePerSfYear),0)/21780; expect(n(result.resolvedLeasing?.rentalRatePerSfYear)).toBeCloseTo(expected,12); });
  it('uses tenant-row costs while retaining weighted descriptive assumptions', () => { const ti=result.tenants.reduce((a,t)=>a+n(t.tenantImprovementTotal),0); const lc=result.tenants.reduce((a,t)=>a+n(t.leasingCommissionTotal),0); const free=result.tenants.reduce((a,t)=>a+n(t.freeRentTotal),0); expect(n(result.developmentCosts?.tenantImprovements)).toBeCloseTo(ti,8); expect(n(result.developmentCosts?.leasingCommissions)).toBeCloseTo(lc,8); expect(n(result.developmentCosts?.freeRentCost)).toBeCloseTo(free,8); expect(result.resolvedLeasing?.annualRentBump).toBeDefined(); expect(result.diagnostics.some(d=>d.code==='WEIGHTED_ASSUMPTION_COST_DIFFERENCE')).toBe(true); });
  it('creates five years and catch-alls', () => { expect(result.leaseUpSchedule).toHaveLength(7); expect(result.leaseUpSchedule.at(-1)?.cumulativeSf).toBe('21780'); expect(result.diagnostics.some(d=>d.code==='LEASE_UP_SCHEDULE_RECONCILIATION_FAILURE')).toBe(false); });
  it('warns when under-leased', () => { const i=clone(canonicalInput); if(i.leasing.mode==='tenantRoster')i.leasing.tenants.pop(); expect(calculateRetailDevelopmentUnderwriting(i).diagnostics.some(d=>d.code==='TENANT_SF_BELOW_GLA')).toBe(true); });
  it('warns when over-leased', () => { const i=clone(canonicalInput); if(i.leasing.mode==='tenantRoster')i.leasing.tenants.push({...canonicalTenants[0],name:'Extra',displayOrder:9}); expect(calculateRetailDevelopmentUnderwriting(i).diagnostics.some(d=>d.code==='TENANT_SF_ABOVE_GLA')).toBe(true); });
  it('blocks an empty roster', () => { const i=clone(canonicalInput); if(i.leasing.mode==='tenantRoster')i.leasing.tenants=[]; const r=calculateRetailDevelopmentUnderwriting(i); expect(r.complete).toBe(false); expect(r.resolvedLeasing).toBeNull(); expect(r.opportunityScreen).toBeNull(); });
  it('handles zero GLA without non-finite output', () => { const i=clone(canonicalInput); i.site.targetFar=0; const r=calculateRetailDevelopmentUnderwriting(i); expect(r.complete).toBe(true); expect(r.diagnostics.some(d=>d.code==='ZERO_GLA')).toBe(true); expect(JSON.stringify(r)).not.toMatch(/NaN|Infinity/); });
  it('warns for canonical late and unscheduled tenants without blocking', () => { expect(result.complete).toBe(true); expect(result.diagnostics.some(d=>d.code==='TENANT_COMMENCEMENT_AFTER_STABILIZATION')).toBe(true); expect(result.diagnostics.some(d=>d.code==='UNSCHEDULED_SF_AT_STABILIZATION')).toBe(true); expect(result.diagnostics.some(d=>d.code==='ROSTER_NOT_FULLY_SCHEDULED_AT_STABILIZATION')).toBe(true); });
});

describe('lease-up cash symmetry',()=>{
  const withNetCash=(amount:number)=>{const i=clone(marketInput);i.leaseUp.averageOccupancyRate=.5;i.leaseUp.nnnOperatingExpensesPerSfYear=28-amount/10890;return calculateRetailDevelopmentUnderwriting(i)};
  const zero=withNetCash(0),surplus=withNetCash(100),deficit=withNetCash(-100);
  it('nets a $100 surplus against equity exactly once',()=>{expect(n(surplus.leaseUpEconomics?.netLeaseUpOperatingCashFlow)).toBeCloseTo(100,8);expect(n(zero.sourcesAndUses?.netEquityInvested)-n(surplus.sourcesAndUses?.netEquityInvested)).toBeCloseTo(100,8);expect(n(surplus.equityReturns?.netCashToEquityAtSale)).toBeCloseTo(n(zero.equityReturns?.netCashToEquityAtSale),8);expect(n(surplus.equityReturns?.equityProfit)-n(zero.equityReturns?.equityProfit)).toBeCloseTo(100,8);});
  it('funds a $100 deficit exactly once',()=>{expect(n(deficit.leaseUpEconomics?.netLeaseUpOperatingCashFlow)).toBeCloseTo(-100,8);expect(n(deficit.sourcesAndUses?.netEquityInvested)-n(zero.sourcesAndUses?.netEquityInvested)).toBeCloseTo(100,8);expect(n(deficit.equityReturns?.netCashToEquityAtSale)).toBeCloseTo(n(zero.equityReturns?.netCashToEquityAtSale),8);expect(n(zero.equityReturns?.equityProfit)-n(deficit.equityReturns?.equityProfit)).toBeCloseTo(100,8);});
  it('has no equity adjustment at zero cash flow',()=>{expect(n(zero.leaseUpEconomics?.leaseUpOperatingDeficit)).toBeCloseTo(0,8);expect(n(zero.leaseUpEconomics?.leaseUpOperatingSurplus)).toBeCloseTo(0,8);expect(n(zero.sourcesAndUses?.grossEquityFundingRequirement)).toBeCloseTo(n(zero.sourcesAndUses?.netEquityInvested),8);});
  it.each([surplus,zero,deficit])('reconciles gross and net sources',(r)=>{const s=r.sourcesAndUses!;expect(n(s.debtFunding)+n(s.grossEquityFundingRequirement)).toBeCloseTo(n(s.grossProjectUses),8);expect(n(s.debtFunding)+n(s.netEquityInvested)+n(s.leaseUpOperatingSurplus)).toBeCloseTo(n(s.grossProjectUses),8);expect(s.sourcesAndUsesDifference).toBe('0');});
});

describe('stabilization diagnostics',()=>{
  const roster=(late:boolean,unscheduled:boolean)=>{const i=clone(canonicalInput);if(i.leasing.mode==='tenantRoster')i.leasing.tenants=i.leasing.tenants.map((t,index)=>({...t,leaseCommencementDate:unscheduled&&index===7?null:late&&index===6?'2028-11-01':'2028-01-01'}));return calculateRetailDevelopmentUnderwriting(i)};
  it('emits no stabilization warning when all tenants commence by sale',()=>{const r=roster(false,false);expect(r.diagnostics.some(d=>d.code.includes('STABILIZATION'))).toBe(false);});
  it('warns for a tenant after stabilization',()=>{const r=roster(true,false);expect(r.complete).toBe(true);expect(r.diagnostics.some(d=>d.code==='TENANT_COMMENCEMENT_AFTER_STABILIZATION')).toBe(true);expect(r.diagnostics.some(d=>d.code==='UNSCHEDULED_SF_AT_STABILIZATION')).toBe(false);});
  it('warns for unscheduled SF',()=>{const r=roster(false,true);expect(r.complete).toBe(true);expect(r.diagnostics.some(d=>d.code==='UNSCHEDULED_SF_AT_STABILIZATION')).toBe(true);expect(r.diagnostics.some(d=>d.code==='TENANT_COMMENCEMENT_AFTER_STABILIZATION')).toBe(false);});
  it('emits both warnings with context when both apply',()=>{const r=roster(true,true);const late=r.diagnostics.find(d=>d.code==='TENANT_COMMENCEMENT_AFTER_STABILIZATION');const missing=r.diagnostics.find(d=>d.code==='UNSCHEDULED_SF_AT_STABILIZATION');expect(late?.context?.affectedSf).toBe('3000');expect(missing?.context?.unscheduledSf).toBe('780');expect(r.complete).toBe(true);});
});

describe('validation', () => {
  it.each([['negative land',(i:typeof marketInput)=>{i.site.landAreaSf=-1},'INVALID_NONNEGATIVE_VALUE'],['zero cap',(i:typeof marketInput)=>{i.disposition.exitCapRate=0},'INVALID_EXIT_CAP_RATE'],['bad LTC',(i:typeof marketInput)=>{i.financing.loanToCost=1.1},'INVALID_RATE'],['bad occupancy',(i:typeof marketInput)=>{i.leaseUp.averageOccupancyRate=-.1},'INVALID_RATE'],['bad vacancy',(i:typeof marketInput)=>{i.operations.vacancyCreditLossRate=2},'INVALID_RATE'],['fractional term',(i:typeof marketInput)=>{if(i.leasing.mode==='market')i.leasing.leaseTermMonths=60.5},'INVALID_MONTHS']] as const)('blocks %s',(_label,mutate,code)=>{const i=clone(marketInput);mutate(i);const r=calculateRetailDevelopmentUnderwriting(i);expect(r.complete).toBe(false);expect(r.diagnostics.some(d=>d.code===code)).toBe(true);expect(r.opportunityScreen).toBeNull();});
  it('exposes standalone validation',()=>expect(validateInput(marketInput)).toEqual([]));
});

describe('screen boundaries',()=>{
  it.each([['0.0099','PASS'],['0.01','REVIEW'],['0.0199','REVIEW'],['0.02','PURSUE'],['0.025','PURSUE']] as const)('classifies %s',(spread,expected)=>{const base=calculateRetailDevelopmentUnderwriting(marketInput);const i=clone(marketInput);i.disposition.exitCapRate=new Decimal(base.unleveredReturns!.returnOnCost!).minus(spread).toString();expect(calculateRetailDevelopmentUnderwriting(i).opportunityScreen).toBe(expected);});
});

describe('sensitivity and regression invariants',()=>{
  const result=calculateRetailDevelopmentUnderwriting(canonicalInput);
  it('reconciles both base cells exactly',()=>{expect(result.sensitivities?.unleveredProfitByRentAndExitCap.cells[2][2]).toBe(result.unleveredReturns?.unleveredProfit);expect(result.sensitivities?.returnOnCostByHardCostAndRent.cells[2][2]).toBe(result.unleveredReturns?.returnOnCost);});
  it('tenant-roster rent sensitivity aggregates scaled tenant costs',()=>{const matrix=result.sensitivities!.unleveredProfitByRentAndExitCap;expect(n(matrix.cells[3][2])).toBeGreaterThan(n(matrix.cells[2][2]));const scaled=clone(canonicalInput);if(scaled.leasing.mode==='tenantRoster')scaled.leasing.tenants=scaled.leasing.tenants.map(t=>({...t,rentalRatePerSfYear:new Decimal(t.rentalRatePerSfYear).times('1.05').toString()}));const direct=calculateRetailDevelopmentUnderwriting(scaled);expect(matrix.cells[3][2]).toBe(direct.unleveredReturns?.unleveredProfit);expect(n(direct.developmentCosts?.leasingCommissions)).toBeCloseTo(direct.tenants.reduce((a,t)=>a+n(t.leasingCommissionTotal),0),7);expect(n(direct.developmentCosts?.freeRentCost)).toBeCloseTo(direct.tenants.reduce((a,t)=>a+n(t.freeRentTotal),0),7);});
  it('higher rent increases NOI',()=>{const a=clone(marketInput),b=clone(marketInput);if(a.leasing.mode==='market'&&b.leasing.mode==='market'){a.leasing.rentalRatePerSfYear=25;b.leasing.rentalRatePerSfYear=30}expect(n(calculateRetailDevelopmentUnderwriting(b).stabilizedOperations?.netOperatingIncome)).toBeGreaterThan(n(calculateRetailDevelopmentUnderwriting(a).stabilizedOperations?.netOperatingIncome));});
  it('higher cap lowers sale value',()=>{const a=clone(marketInput),b=clone(marketInput);a.disposition.exitCapRate=.055;b.disposition.exitCapRate=.07;expect(n(calculateRetailDevelopmentUnderwriting(b).disposition?.grossSaleValue)).toBeLessThan(n(calculateRetailDevelopmentUnderwriting(a).disposition?.grossSaleValue));});
  it('higher hard cost lowers return on cost',()=>{const a=clone(marketInput),b=clone(marketInput);a.development.hardCostPerBuildingSf=170;b.development.hardCostPerBuildingSf=220;expect(n(calculateRetailDevelopmentUnderwriting(b).unleveredReturns?.returnOnCost)).toBeLessThan(n(calculateRetailDevelopmentUnderwriting(a).unleveredReturns?.returnOnCost));});
  it('pins canonical outputs',()=>{expect(result.geometry?.buildingAreaSf).toBe('21780');expect(result.timeline?.constructionCompletion).toBe('2027-10-01');expect(result.resolvedLeasing?.totalRosterSf).toBe('21780');expect(result.developmentCosts?.developmentCostBeforeFinancing).toMatch(/^8/);expect(result.leaseUpSchedule.at(-1)?.cumulativeSf).toBe('21780');});
});
